<?php

namespace Database\Seeders;

use App\Models\Position;
use App\Models\PositionJobDetail;
use Illuminate\Database\Seeder;

class PositionJobDetailSeeder extends Seeder
{
    public function run(): void
    {
        $details = [
            'UNIV-LIB' => [
                'salary_scale' => 'M3',
                'reports_to' => 'Vice-Chancellor',
                'responsible_for' => 'Deputy University Librarian',
                'job_purpose' => 'The University Librarian is the Head of the University Library and is responsible for the development, control, management and coordination of all library and information services of the University.',
                'duties' => [
                    'Plan for and implement, in liaison with relevant departments of the University, the various projects and programs of the Library.',
                    'Become familiar with the programs offered by the University and liaise with faculty heads on Library development so relevant information materials are provided to the university community.',
                    'Hold and chair regular Library Management and Committee meetings.',
                    'Keep in constant touch with developments in the world of information to ensure relevant and up-to-date information is provided to University staff and students.',
                    'Ensure the creation and maintenance of Library databases that give the University community easy access to information resources.',
                    'Work closely with University leadership to focus on and prioritize Library plans and developments.',
                    'Plan for Library staff development, including training and promotion, with the Director of Human Resources and keep staff abreast of professional developments.',
                    'Develop and update Library rules, regulations and guidelines for access to and use of Library materials in line with internationally acceptable standards.',
                    'Assess and appraise senior Library staff.',
                    'Represent the University at national and international events.',
                    'Develop partnerships with academic, research and public libraries and library associations at regional, national and international levels.',
                    'Support and strengthen Busitema University campus libraries.',
                    'Spearhead and promote community outreach and service that positions the role of the Library in the community.',
                    'Ensure equitable access to information resources, services, facilities and systems in physical and virtual environments.',
                    'Undertake any other related duties necessary to ensure efficient and effective library and information services in the University.',
                ],
            ],
            'DEP-UNIV-LIB' => [
                'salary_scale' => 'M4',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Senior Librarian',
                'job_purpose' => 'Deputizes the University Librarian.',
                'duties' => [
                    'Assist the University Librarian in the management, supervision and administration of the Library.',
                    'Supervise the provision of Library services in accordance with Library policies.',
                    'Serve on all Library Committees and as Secretary to all Library Committees.',
                    'Facilitate communication and coordination with other departments in the Library.',
                    'Engage in research and publications.',
                    'Represent the University Librarian in different forums in their absence.',
                    'Coordinate the activities of campus librarians to foster equitable access to information resources at all campuses.',
                    'Carry out any other duties assigned by the University Librarian.',
                ],
            ],
            'SR-LIB-TECH' => [
                'salary_scale' => 'M5',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Librarian',
                'job_purpose' => 'As Chief Cataloguer and Head of Technical Services, coordinates the overall information processing function of the Library.',
                'duties' => [
                    'Perform full original and copy cataloguing of books and materials using established standards.',
                    'Prepare cataloguing data for input and assign codes and tags accurately.',
                    'Keep up to date with revisions in cataloguing rules and practices.',
                    'Share information about new cataloguing rules and practices and apply that knowledge as appropriate.',
                    'Supervise copy cataloguing performed by subordinates and answer their questions.',
                    'Systematically review cataloguing performed by subordinates for accuracy and make corrections as necessary.',
                    'Supervise the physical processing of materials and ensure cataloguing and labelling are accurate and neat.',
                    'Establish correct authority records for names, series, subjects and uniform titles.',
                    'Correct and resolve problems related to obsolete, conflicting or incorrect older cataloguing.',
                    'Work with campus libraries to ensure acquired materials are delivered and shelved on time.',
                    'Prepare and provide collection reports as scheduled or requested.',
                    'Engage in research, publication and grant proposal writing.',
                    'Collect and check subject bibliographies for assessment.',
                    'Serve on the Library Senior Management, Finance, Appointments and Promotions, and Collections Committees.',
                    'Facilitate communication and coordination with other departments in the Library.',
                ],
            ],
            'SR-LIB-DIG' => [
                'salary_scale' => 'M5',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Librarian',
                'job_purpose' => 'Leads, administers and coordinates the development, deployment and provision of effective digital technologies and technology-based services.',
                'duties' => [
                    "Design and implement a strategic roadmap that uses digital technologies to advance the Library's objectives in support of teaching, learning and research.",
                    'Work with campus librarians to develop and implement strategy, policy and procedures for requesting and implementing technology projects.',
                    'Develop and implement a centralized approach to digital technology project management at the Library.',
                    'Prepare and manage the Library IT budget.',
                    'Oversee procurement and maintenance of hardware, software, web services, contracts and licences in liaison with the University ICT department.',
                    'Participate in Library planning, including strategic planning, administrative coordination, policy development and alignment of services with strategic objectives.',
                    'Participate in internal and external partnerships with Quality Assurance, Graduate Research, Training and Innovation, ICT Support, Academic Registrar and campus leadership teams.',
                    "Advocate for the Library's institutional repository, seek contributors and publicize its benefits and uses.",
                    'Define and manage digital collections with the Directorate of ICT on systems and technology and with Library staff on suitable metadata schemes.',
                    'Develop services that support scholarship and scholarly communication, including open access, intellectual property, data curation and new forms of publication and research.',
                    'Serve on all Library Committees and facilitate communication and coordination with other Library departments.',
                    'Perform any other duties assigned by the University Librarian.',
                ],
            ],
            'SR-LIB-CURS' => [
                'salary_scale' => 'M5',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Librarian',
                'job_purpose' => 'Heads the User and Reference Services Department and fosters a creative, collaborative and team-oriented work environment.',
                'duties' => [
                    'Lead the development of user services policies and procedures.',
                    'Conduct research and collect usage statistics for all collections.',
                    'Serve on all Library Committees and facilitate communication and coordination with other Library departments.',
                    'Develop, evaluate and implement innovative, user-focused academic information and resource services for the University community.',
                    'Foster an environment of responsive, welcoming services and spaces.',
                    'Contribute to the design of emerging user-services technologies.',
                    'Develop approaches to public-service delivery that support University teaching, learning and research.',
                    'Perform any other duties assigned by the University Librarian.',
                ],
            ],
            'SR-LIB-ARCH' => [
                'salary_scale' => 'M5',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Librarian',
                'job_purpose' => 'Heads Special Collections and Archives, serves as University Curator, and fosters the use of special collections through research and support for teaching and learning.',
                'duties' => [
                    'Coordinate the identification, appraisal, acquisition, storage, access, preservation and disposal of Library archives in paper and electronic formats.',
                    'Organize archival collections to ensure their long-term preservation.',
                    'Create archival-based descriptions.',
                    'Provide online and in-house archival reference services and investigate, assess and acquire potential collections.',
                    'Write grant proposals related to archival work.',
                    'Conduct outreach programmes for the University community and participate in instructional sessions.',
                    'Participate collaboratively in Library exhibits, design and fabrication, and digitization initiatives.',
                    "Provide curator engagement for the University's iconographic pieces.",
                    'Act as liaison between the Library and University administration in collecting University archives.',
                    "Engage in research leading to publications and national service to meet the Libraries' and University's requirements for academic status.",
                    'Ensure that special collections and archives are well described and cared for.',
                    'Develop initiatives using new technologies to encourage broad scholarly and educational use of primary sources.',
                    'Cultivate strong ties with teaching staff so use of special collections remains an active part of the curriculum.',
                    'Pursue and implement grants for improved access, conservation and public programming.',
                    'Serve on all Library Committees and facilitate communication and coordination with other Library departments.',
                    'Perform any other assigned duties.',
                ],
            ],
            'SR-LIB-ERES' => [
                'salary_scale' => 'M5',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Librarian',
                'job_purpose' => 'Oversees the timely acquisition of all library and information resources.',
                'duties' => [
                    'Develop strategies, processes and workflows to acquire content in all formats.',
                    'Ensure information resources are acquired in a timely, fiscally responsible and effective manner.',
                    'Provide management and leadership for the Acquisitions Management Section.',
                    'Liaise with the Library Administrator, Electronic Resources and Serials Management teams to make e-resource payments.',
                    'Coordinate electronic-resource acquisition, licensing and access management across the University Library System with campus librarians and service teams.',
                    'In consultation with the Head of Technical Services, allocate, monitor and report on the acquisitions budget and expenditure.',
                    'Engage publishers, vendors, subscription agents and consortia to acquire content and evaluate their services.',
                    'Maintain an understanding of best practices and trends in collection procurement and scholarly publishing and alert colleagues as appropriate.',
                    'Apply best practices to provide excellent user-centred services.',
                    'Serve as a resource person on e-library materials acquisition for Technical Services, Digitization and other University personnel.',
                    'Work collegially with campus librarians and academic staff by providing expertise on local and overseas acquisitions.',
                    'Serve on all Library Committees and facilitate communication and coordination with other Library departments.',
                ],
            ],
            'CAMP-LIB' => [
                'salary_scale' => 'M5',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'Senior Librarian',
                'job_purpose' => 'Heads the campus library and is responsible for the development, control, management and coordination of all library and information services of the campus.',
                'duties' => [
                    'Deputize the University Librarian in the faculty and serve as Library liaison to the faculty or campus.',
                    'Assist the University Librarian in managing and supervising the faculty library and provide efficient services under Library policies and procedures.',
                    'Mentor faculty Library staff through orientation, training, workload organization, timesheet enforcement, delegation, guidance, performance monitoring, coaching, counselling and discipline.',
                    'Serve on Faculty Academic Affairs and Library Committees and participate in faculty academic activities, including curriculum and collection development.',
                    'Lead day-to-day faculty Library operations, reference and research services, timetabling, cleanliness, physical organization and liaison with faculty deans.',
                    'Prepare and defend annual campus Library budget proposals.',
                    'Direct and control use of campus Library materials within approved budgets.',
                    'Serve on Library Committees and coordinate with Technical Services, Digitization, ICT, Conservation, Preservation and Restoration departments.',
                    'Provide leadership, guidance and strategic direction to Campus User Services and foster a collaborative, team-oriented environment.',
                    "Advocate for the Library's e-services and institutional repository, seek contributors and publicize their benefits and uses.",
                    'Select new books and journals for the faculty Library in consultation with academic staff.',
                    'Conduct periodic book-stock checks and annual stocktaking of Library information materials.',
                    'Participate in developing, implementing and enforcing Library policies and procedures at the faculty.',
                    'Prepare statistical reports on circulation, reference enquiries, finances, stock and user services under performance-evaluation guidelines.',
                    'Participate in selecting, acquiring and preserving faculty Library collections under the Collection Development Policy.',
                    'Train staff and students to access Library services and coordinate specialized information-literacy training.',
                    'Initiate Library marketing strategies to promote services and collections in the faculty or campus.',
                    'Engage in research, publication and grant proposal writing.',
                    'Perform any other duties assigned by the University Librarian.',
                ],
            ],
            'SR-LIB' => [
                'salary_scale' => 'M5',
                'reports_to' => 'Campus Librarian',
                'responsible_for' => 'Librarian',
                'job_purpose' => 'Responsible for the development, control, management and coordination of assigned library and information services.',
                'duties' => [
                    'Engage in innovative research and publication that improves Library service delivery.',
                    'Participate in Library programming, exhibitions, marketing of resources and services, and research grant proposal writing.',
                    'Offer specialized support to academics and develop Library tools that support access to collections.',
                    'Perform responsible professional Library duties requiring judgement, detail and accuracy in serving students and staff.',
                    'Supervise lower-ranked librarians in the absence of the Campus Librarian.',
                    'Perform administrative, reference, technical-services, collection-development, programming, circulation and general Library activities.',
                    'Report to the Campus Librarian.',
                ],
            ],
            'LIB' => [
                'salary_scale' => 'M6.1',
                'reports_to' => 'Senior Librarian',
                'responsible_for' => 'Assistant Librarian',
                'job_purpose' => 'Assists the Campus Librarian in the management, supervision and administration of the faculty library in accordance with Library policies and procedures.',
                'duties' => [
                    'Coordinate and maintain content for web and mobile-enabled interactive services that provide a quality user experience.',
                    'Collaborate with IT staff to develop information-service strategies that maintain patron satisfaction with on-site and digital technology resources.',
                    'Develop and deliver patron instruction on print and digital collections and technologies, including Library programmes.',
                    'Perform professional collection-development work, including acquisition, automated cataloguing, digitization, reference, circulation, evaluation, selection, stocktaking and weeding.',
                    'Provide information, readers-advisory and reference services.',
                    'Keep informed of professional and technological developments through organizations, workshops, continuing education and professional reading.',
                    "Coordinate access to and maintenance of the Library's print and digital resources.",
                    'Work cooperatively with librarians and support staff to promote print and digital resources to the University community.',
                    'Collect, maintain and report statistics on print and digital resources and services through the immediate supervisor.',
                    'Participate in collection-development activities.',
                    'Supervise Library staff performing weekend duties on a rotating schedule.',
                    'Perform other assigned duties.',
                ],
            ],
            'ASST-LIB' => [
                'salary_scale' => 'M6.2',
                'reports_to' => 'Librarian',
                'responsible_for' => 'Library Assistant',
                'job_purpose' => 'Assists the Campus Librarian in the supervision and administration of the faculty library in accordance with Library policies and procedures.',
                'duties' => [
                    'Assist with coordinating and maintaining content for web and mobile-enabled interactive services that provide a quality user experience.',
                    'Collaborate with IT staff to develop information-service strategies that maintain patron satisfaction with on-site and digital technology resources.',
                    'Develop and deliver patron instruction on print and digital collections and technologies, including Library programmes.',
                    'Perform professional collection-development work, including acquisition, automated cataloguing, digitization, reference, circulation, evaluation, selection, stocktaking and weeding.',
                    'Provide information, readers-advisory and reference services.',
                    'Keep informed of professional and technological developments through organizations, workshops, continuing education and professional reading.',
                    "Coordinate access to and maintenance of the Library's print and digital resources.",
                    'Work cooperatively with librarians and support staff to promote print and digital resources to the University community.',
                    'Collect, maintain and report statistics on print and digital resources and services through the immediate supervisor.',
                    'Participate in collection-development activities.',
                    'Supervise Library staff performing weekend duties on a rotating schedule.',
                    'Perform other assigned duties.',
                ],
            ],
            'LIB-AST' => [
                'salary_scale' => 'M7',
                'reports_to' => 'Assistant Librarian',
                'responsible_for' => 'Senior Library Clerk',
                'job_purpose' => 'Provides specialized reference services in the respective campus library.',
                'duties' => [
                    'Engage in research and publication.',
                    'Participate in information-literacy instruction for Library users in physical and virtual settings.',
                    'Create handouts, guides and other Library materials that enhance student learning and perform related duties as needed.',
                    'Provide general and specialized information and research assistance virtually and in person.',
                    'Participate in developing policies and procedures for Library services.',
                    'Participate in identifying, implementing and managing emerging technologies and best practices.',
                    'Participate in cataloguing, classification, general processing of Library materials and bibliographic control.',
                    'Compile Library statistics.',
                    'Help users with general Library use and access to online information resources.',
                    'Advise students and staff on the use of information resources.',
                    'Participate in collection-development activities.',
                    'Perform weekend duties on a rotating schedule.',
                    'Perform any other duties assigned by the Campus Librarian.',
                ],
            ],
            'LIB-SYS' => [
                'salary_scale' => 'M6.1',
                'reports_to' => 'Senior Librarian - Digital Services',
                'responsible_for' => 'Assistant Librarian - Systems Administrator',
                'job_purpose' => 'Effectively develops and maintains the Library ICT infrastructure and digital computing services.',
                'duties' => [
                    'Ensure Library automation and ICT applications function properly.',
                    'Lead installation, configuration, operation and maintenance of systems hardware, software and related infrastructure.',
                    "Manage the Library's servers, including installation and upgrades.",
                    'Participate in technical research and development to enable continuing infrastructure innovation.',
                    "Ensure systems hardware, operating systems, software and procedures adhere to the Library's values and enable staff and students.",
                    'Provide hardware support for laptops, desktop computers, printers, scanners and Library technologies such as self-check circulation equipment.',
                    'Configure hardware devices, test new software and design the network structure.',
                ],
            ],
            'ASST-LIB-SYS' => [
                'salary_scale' => 'M7',
                'reports_to' => 'Librarian - Systems Librarian',
                'responsible_for' => 'Senior Library Clerk - ICT Technician',
                'job_purpose' => "Assists the Systems Librarian in managing the Library's ICT infrastructure.",
                'duties' => [
                    'Support Library automation and ICT applications to function properly.',
                    'Support installation, configuration, operation and maintenance of systems hardware, software and related infrastructure.',
                    "Maintain the Library's servers, including installation and upgrades.",
                    'Participate in technical research and development to enable continuing infrastructure innovation.',
                    "Ensure systems hardware, operating systems, software and procedures adhere to the Library's values and enable staff and students.",
                    'Provide hardware support for laptops, desktop computers, printers, scanners and Library technologies such as self-check circulation equipment.',
                ],
            ],
            'ADMIN-SEC' => [
                'salary_scale' => 'M6.2',
                'reports_to' => 'University Librarian',
                'responsible_for' => 'None',
                'job_purpose' => 'Assists the University Librarian in managing Library assets and resources.',
                'duties' => [
                    'Ensure procurement policies and procedures are followed.',
                    "Maintain the Library's asset register.",
                    'Manage Library store materials.',
                    'Participate in drafting the Library budget.',
                    'Ensure payments are completed on time following the required financial procedures.',
                    'Report to the University Librarian.',
                ],
            ],
            'LIB-HEAD-BIND' => [
                'salary_scale' => 'M6.1',
                'reports_to' => 'Archivist / Special Collections Librarian / Head of Special Collections & Archives - University Curator',
                'responsible_for' => 'Library Assistant - Book Binder',
                'job_purpose' => 'Heads the Bindery Section and is responsible for maintaining all kinds of Library collections.',
                'duties' => [
                    'Head the Bindery Section.',
                    'Assist the Campus Librarian in day-to-day operation of the Bindery as an income-generating unit.',
                    'Improve the quality and quantity of Bindery output and devise measures for quality and timely delivery.',
                    'Lead training of Bindery staff.',
                    'Maintain equipment and select binding materials.',
                    'Carry out any other Bindery or Library work assigned by the Archivist.',
                ],
            ],
            'LIB-AST-BIND' => [
                'salary_scale' => 'M7',
                'reports_to' => 'Librarian - Head Binder',
                'responsible_for' => 'Senior Library Clerk - Senior Book Binder',
                'job_purpose' => 'Assists the Head Binder in Bindery processes.',
                'duties' => [
                    'Receive and forward binding materials.',
                    'Participate in binding repairs.',
                    'Participate in sewing and pulling books.',
                    'Perform any other duties assigned by the Head Binder.',
                ],
            ],
            'SR-CLERK-BIND' => [
                'salary_scale' => 'M10',
                'reports_to' => 'Library Assistant - Book Binder',
                'responsible_for' => 'Library Clerk - Assistant Binder',
                'job_purpose' => 'Assists in the day-to-day administration of the Bindery Section.',
                'duties' => [
                    'Organize the Bindery to perform competitive binding work.',
                    'Market Bindery services and perform any other duties described by the Head Binder.',
                    'Report to the Archivist through the Head Binder.',
                ],
            ],
            'SR-CLERK-ICT' => [
                'salary_scale' => 'M10',
                'reports_to' => 'Assistant Librarian - Systems Administrator',
                'responsible_for' => 'Not Assigned',
                'job_purpose' => 'Assists the Assistant Librarian - Systems Administrator in day-to-day Library automation work.',
                'duties' => [
                    'Support Library automation and ICT applications to function properly.',
                    'Support installation, configuration, operation and maintenance of systems hardware, software and related infrastructure.',
                    "Maintain the Library's servers, including installation and upgrades.",
                    "Ensure systems hardware, operating systems, software and procedures adhere to the Library's values and enable staff and students.",
                    'Provide hardware support for laptops, desktop computers, printers, scanners and Library technologies such as self-check circulation equipment.',
                ],
            ],
            'SR-LIB-CLERK' => [
                'salary_scale' => 'M10',
                'reports_to' => 'Library Assistant',
                'responsible_for' => 'None',
                'job_purpose' => 'Responsible for the day-to-day activities of the Library.',
                'duties' => [
                    'Process books.',
                    'Perform cataloguing, circulation, acquisition and stock validation using the Koha Library system under professional supervision.',
                    'Check catalogue records and databases.',
                    'Distribute books.',
                    'Perform data entry.',
                    'File catalogue cards.',
                    'Enter data into Card Master and print catalogue cards.',
                    'Weed, sort and discard materials from the collection.',
                    'Label shelves and organize displays.',
                    'Receive books delivered to the campus Library.',
                    'Check the accuracy of packing lists.',
                    'Check invoices and packing lists against orders.',
                    'Maintain files for audit.',
                    'Register and orient new students at the reference and circulation desk.',
                    'Handle physical, telephone, chat and email enquiries and refer research questions to professional librarians.',
                    'Issue books to and receive books from Library users.',
                    'Rearrange and shelve physical collections in the correct classification order.',
                    'Maintain daily usage statistics for books and users.',
                    'Compile defaulters and follow up overdue books.',
                    'Follow up fines and payments.',
                    'Participate in stocktaking and user-education programmes.',
                    'Keep workplaces organized and tidy and help users locate reading materials.',
                    'Control and monitor use of the e-learning centre and internet-access computers using timing software.',
                    'Provide computer-use support and training to graduate and undergraduate students.',
                    'Help users browse the internet, online journals and other electronic resources.',
                    'Work with Library users to organize events such as International Library Day and exhibitions.',
                    'Update timesheets as part of daily output.',
                    'Attend Library staff meetings and in-house training.',
                    'Set up files according to the filing system.',
                    'Perform any other work assigned by the supervisor.',
                ],
            ],
            'LIB-CLERK' => [
                'salary_scale' => 'M12',
                'reports_to' => 'Library Assistant',
                'responsible_for' => 'None',
                'job_purpose' => 'Responsible for the day-to-day security of Library personnel and resources.',
                'duties' => $this->attendantDuties(),
            ],
            'LIB-ATT' => [
                'salary_scale' => 'M13',
                'reports_to' => 'Library Assistant',
                'responsible_for' => 'None',
                'job_purpose' => 'Responsible for the day-to-day security of Library personnel and resources.',
                'duties' => $this->attendantDuties(),
            ],
            'OFF-ATT' => [
                'salary_scale' => 'M15',
                'reports_to' => 'Library Assistant',
                'responsible_for' => 'None',
                'job_purpose' => 'Responsible for the day-to-day security of Library personnel and resources.',
                'duties' => $this->attendantDuties(),
            ],
        ];

        // Only the standard positions are seeded. Job descriptions that administrators
        // write for positions added later are left untouched when seeding re-runs.
        foreach ($details as $code => $detail) {
            $position = Position::where('code', $code)->firstOrFail();

            PositionJobDetail::updateOrCreate(
                ['position_id' => $position->id],
                $detail
            );
        }
    }

    /** @return array<int, string> */
    private function attendantDuties(): array
    {
        return [
            'Ensure the security of Library premises, materials and equipment.',
            'Ensure books and other reading materials are secure.',
            'Follow precautionary measures when opening and closing the Library.',
            'Scout interior and exterior Library spaces whenever the Library is open.',
            'During power blackouts, secure all Library spaces and help students leave safely.',
            'Monitor water points to ensure they remain secure and do not leak.',
            'Ensure all lights are switched off when closing the Library.',
            'Ensure all windows are closed to safeguard Library materials.',
            'Periodically check users to ensure prohibited materials are not brought into the Library.',
            'Keep the Library reading environment free from noise caused by users and other sources.',
            'Perform any other work assigned by the supervisor.',
        ];
    }
}
