@extends('layouts.app')
@section('title', $report->report_code)
@section('section-label', 'Reports')
@section('page-title', 'Monthly Report Review')
@section('content')
<div class="mx-auto max-w-screen-2xl">
    <a href="{{ route('monthly-reports.reviews.index') }}" class="text-sm font-semibold text-emerald-700">&larr; Back to Reports Awaiting My Review</a>
    <header class="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="font-mono text-sm font-bold text-emerald-700">{{ $report->report_code }}</p><h2 class="mt-2 text-3xl font-bold text-slate-900">{{ data_get($snapshot,'period.label') }}</h2><p class="mt-2 text-slate-600">Submitted by {{ $report->submitter?->name ?? $report->user->name }} on {{ $report->submitted_at?->format('d F Y, h:i A') }}.</p></div><span @class(['rounded-full px-3 py-1.5 text-sm font-semibold','bg-blue-50 text-blue-800'=>$report->status===App\Models\MonthlyReport::STATUS_PENDING_REVIEW,'bg-red-50 text-red-800'=>$report->status===App\Models\MonthlyReport::STATUS_RETURNED_FOR_CORRECTION,'bg-emerald-50 text-emerald-800'=>$report->status===App\Models\MonthlyReport::STATUS_APPROVED])>{{ App\Models\MonthlyReport::label($report->status) }}</span></header>

    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h3 class="text-lg font-bold">Staff Information</h3></div><dl class="grid gap-px bg-slate-200 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Name',data_get($snapshot,'staff.name')],['Position',data_get($snapshot,'staff.position')],['Campus',data_get($snapshot,'staff.campus')],['Library',data_get($snapshot,'staff.library')],['Supervisor',data_get($snapshot,'staff.supervisor')]] as [$label,$value])<div class="bg-white p-5"><dt class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</dt><dd class="mt-2 font-semibold">{{ $value ?: '—' }}</dd></div>@endforeach</dl></section>

    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 class="text-lg font-bold">Performance Summary</h3><div class="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4">@foreach([['Total Hours',data_get($snapshot,'performance.total_hours')],['Days Reported',number_format(data_get($snapshot,'performance.days_reported',0))],['Tasks Assigned',number_format(data_get($snapshot,'performance.tasks_assigned',0))],['Tasks Completed',number_format(data_get($snapshot,'performance.tasks_completed',0))],['Pending Tasks',number_format(data_get($snapshot,'performance.pending_tasks',0))],['Overdue Tasks',number_format(data_get($snapshot,'performance.overdue_tasks',0))],['Completion Rate',number_format(data_get($snapshot,'performance.completion_rate',0),1).'%'],['Project Performance',number_format(data_get($snapshot,'performance.project_performance',0),1).'%']] as [$label,$value])<div class="rounded-xl border border-slate-200 bg-slate-50 p-4"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-slate-700">{{ $value }}</p></div>@endforeach</div></section>

    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 class="text-lg font-bold">Staff Narrative</h3><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach([['key_achievements','Key Achievements','No achievements/deliverables recorded for this period.'],['challenges','Challenges','No challenges recorded for this period.'],['corrective_actions','Corrective Actions','No corrective actions recorded for this period.'],['support_required','Support Required','No support requirements recorded for this period.'],['planned_activities_next_month','Planned Activities for Next Month','No planned follow-up activities recorded for this period.']] as [$field,$label,$empty])<article @class(['rounded-xl border border-slate-200 bg-slate-50 p-5','md:col-span-2'=>$loop->last])><h4 class="font-bold">{{ $label }}</h4>@if(data_get($snapshot,"narrative.$field"))<ul class="mt-3 list-disc space-y-2 pl-5 text-slate-700">@foreach(data_get($snapshot,"narrative.$field") as $item)<li class="whitespace-pre-line">{{ $item }}</li>@endforeach</ul>@else<p class="mt-3 text-sm text-slate-500">{{ $empty }}</p>@endif</article>@endforeach</div></section>

    @if($report->status===App\Models\MonthlyReport::STATUS_PENDING_REVIEW)
        <section class="mt-6 grid gap-5 lg:grid-cols-2"><form method="POST" action="{{ route('monthly-reports.approve',$report) }}" class="rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm">@csrf<h3 class="text-lg font-bold">Approve Report</h3><label class="mt-4 block text-sm font-semibold">Supervisor Remark (optional)<textarea name="approval_remark" rows="4" maxlength="3000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('approval_remark') }}</textarea></label><button class="mt-4 rounded-xl bg-emerald-800 px-5 py-3 font-semibold text-white">Approve Report</button></form><form method="POST" action="{{ route('monthly-reports.return',$report) }}" class="rounded-2xl border border-red-200 bg-white p-6 shadow-sm">@csrf<h3 class="text-lg font-bold">Return for Correction</h3><label class="mt-4 block text-sm font-semibold">Correction Reason <textarea name="correction_reason" required rows="4" maxlength="3000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('correction_reason') }}</textarea>@error('correction_reason')<span class="mt-1 block text-sm text-red-600">{{ $message }}</span>@enderror</label><button class="mt-4 rounded-xl bg-red-700 px-5 py-3 font-semibold text-white">Return for Correction</button></form></section>
    @endif

    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 class="text-lg font-bold">Report History</h3><div class="mt-5 space-y-4">@foreach($report->activities->sortByDesc('created_at') as $activity)<article class="border-l-2 border-emerald-200 pl-4"><p class="font-semibold">{{ $activity->event_label }}</p><p class="mt-1 text-sm text-slate-600">{{ $activity->description }}</p>@if(data_get($activity->metadata,'reason'))<p class="mt-1 whitespace-pre-line text-sm text-red-700">Reason: {{ data_get($activity->metadata,'reason') }}</p>@endif<p class="mt-1 text-xs text-slate-500">{{ $activity->user->name }} · {{ $activity->created_at->format('d F Y, h:i A') }}</p></article>@endforeach</div></section>
</div>
@endsection
