@extends('layouts.app')
@section('title', 'Campus Consolidated Monthly Report')
@section('page-title', 'Campus Consolidated Monthly Report')
@section('content')
@php($identity=$data['identity'])
<div class="mx-auto max-w-screen-2xl space-y-6">
    <header class="rounded-2xl bg-slate-950 p-7 text-white shadow-xl">
        <div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-sm font-bold uppercase tracking-[.2em] text-emerald-400">Busitema University</p><h2 class="mt-3 text-3xl font-bold">Campus Consolidated Monthly Report</h2><p class="mt-2 text-slate-300">Centralized Library Staff Performance System</p></div><div class="text-sm lg:text-right"><p class="font-mono font-bold text-emerald-300">{{ $report?->report_code ?? 'Live draft — code assigned on finalization' }}</p><p class="mt-2">{{ $identity['campus'] }} · {{ $identity['period'] }}</p><span class="mt-3 inline-block rounded-full px-3 py-1 font-semibold {{ $isFrozen ? 'bg-emerald-700' : 'bg-amber-600' }}">{{ $isFrozen ? 'Finalized snapshot' : 'Live draft' }}</span></div></div>
    </header>
    @php($exportParams=['month'=>$identity['month'],'year'=>$identity['year']])
    <div class="flex flex-wrap items-center justify-between gap-3"><a href="{{ auth()->user()->hasRole('University Librarian') ? route('university-dashboard.index', $exportParams) : route('campus-reports.index') }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2 font-semibold">{{ auth()->user()->hasRole('University Librarian') ? 'Back to University Dashboard' : 'Back to History' }}</a><div class="flex flex-wrap gap-2"><a target="_blank" href="{{ $isFrozen ? route('campus-reports.print',$report) : route('campus-reports.print.live',$exportParams) }}" class="rounded-xl border border-emerald-700 bg-white px-4 py-2 font-semibold text-emerald-800">Print Report</a><a href="{{ $isFrozen ? route('campus-reports.pdf',$report) : route('campus-reports.pdf.live',$exportParams) }}" class="rounded-xl bg-emerald-800 px-4 py-2 font-semibold text-white">Download PDF</a><a href="{{ $isFrozen ? route('campus-reports.staff-csv',$report) : route('campus-reports.staff-csv.live',$exportParams) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2 font-semibold">Staff CSV</a><a href="{{ $isFrozen ? route('campus-reports.projects-csv',$report) : route('campus-reports.projects-csv.live',$exportParams) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2 font-semibold">Projects CSV</a>@if(!$isFrozen)<form method="POST" action="{{ route('campus-reports.finalize') }}" onsubmit="return confirm('Finalize and freeze this campus report?')">@csrf<input type="hidden" name="month" value="{{ $identity['month'] }}"><input type="hidden" name="year" value="{{ $identity['year'] }}"><button class="rounded-xl bg-slate-950 px-5 py-2.5 font-semibold text-white">Finalize Campus Monthly Report</button></form>@else<p class="self-center text-sm text-slate-600">Finalized by {{ $report->finalizer?->name }} on {{ $report->finalized_at->format('d F Y, h:i A') }}</p>@endif</div></div>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h3 class="text-lg font-bold">Campus Information</h3></div><dl class="grid gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">@foreach([['Campus',$data['campus']['name']],['Campus Librarian',$data['campus']['campus_librarian']],['Libraries',$data['campus']['libraries']],['Total Staff',$data['campus']['total_staff']],['Active Staff',$data['campus']['active_staff']]] as [$label,$value])<div class="bg-white p-5"><dt class="text-xs font-bold uppercase text-slate-500">{{ $label }}</dt><dd class="mt-2 font-semibold">{{ $value }}</dd></div>@endforeach</dl></section>
    <section><h3 class="mb-3 text-lg font-bold">Campus Performance Summary</h3><div class="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">@foreach([['Total Hours',$data['performance']['total_hours']],['Staff Reporting',$data['performance']['staff_reporting']],['Tasks Assigned',$data['performance']['tasks_assigned']],['Tasks Completed',$data['performance']['tasks_completed']],['In Progress',$data['performance']['tasks_in_progress']],['Pending Review',$data['performance']['pending_review']],['Overdue',$data['performance']['overdue']],['Completion Rate',number_format($data['performance']['completion_rate'],1).'%'],['Active Projects',$data['performance']['active_projects']],['Average Project Progress',number_format($data['performance']['average_project_progress'],1).'%']] as [$label,$value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold">{{ $value }}</p></div>@endforeach</div></section>
    <x-campus-report-table title="Staff Performance Summary" :headers="['Staff','Position','Library','Hours','Days','Assigned','Completed','In Progress','Overdue','Completion','Monthly Report']">
        @forelse($data['staff_rows'] as $row)<tr>@foreach([$row['name'],$row['position'] ?: '—',$row['library'] ?: '—',$row['hours'],$row['days_reported'],$row['tasks_assigned'],$row['completed'],$row['in_progress'],$row['overdue'],number_format($row['completion_rate'],1).'%',str($row['report_status'])->replace('_',' ')->title()] as $cell)<td class="px-4 py-3">{{ $cell }}</td>@endforeach</tr>@empty<tr><td colspan="11" class="p-8 text-center text-slate-500">No active campus staff.</td></tr>@endforelse
    </x-campus-report-table>
    <x-campus-report-table title="Project Performance Summary" :headers="['Code','Project','Status','Progress','Campus Staff','Tasks','Completed','In Progress','Overdue']">
        @forelse($data['project_rows'] as $row)<tr>@foreach([$row['code'],$row['title'],str($row['status'])->replace('_',' ')->title(),number_format($row['progress'],1).'%',implode(', ',$row['staff']),$row['task_count'],$row['completed'],$row['in_progress'],$row['overdue']] as $cell)<td class="px-4 py-3">{{ $cell ?: '—' }}</td>@endforeach</tr>@empty<tr><td colspan="9" class="p-8 text-center text-slate-500">No campus task assignments for this period.</td></tr>@endforelse
    </x-campus-report-table>
    <section class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Task Status Summary</h3><div class="mt-4 grid grid-cols-2 gap-3">@foreach($data['task_status'] as $status=>$count)<div class="rounded-xl bg-slate-50 p-3"><p class="text-xs uppercase text-slate-500">{{ str($status)->replace('_',' ')->title() }}</p><p class="text-xl font-bold">{{ $count }}</p></div>@endforeach</div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Monthly Report Submission Status</h3><div class="mt-4 grid grid-cols-2 gap-3">@foreach($data['report_status'] as $status=>$count)<div class="rounded-xl bg-slate-50 p-3"><p class="text-xs uppercase text-slate-500">{{ str($status)->replace('_',' ')->title() }}</p><p class="text-xl font-bold">{{ $count }}</p></div>@endforeach</div></div></section>
    <section class="grid gap-6 lg:grid-cols-2">@foreach(['achievements'=>'Consolidated Achievements','challenges'=>'Consolidated Challenges','corrective_actions'=>'Consolidated Corrective Actions','support_required'=>'Consolidated Support Required','planned_activities'=>'Planned Activities / Follow-up'] as $key=>$title)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">{{ $title }}</h3><ul class="mt-4 space-y-3">@forelse($data['narrative'][$key] as $item)<li class="rounded-xl bg-slate-50 p-4"><p class="whitespace-pre-line text-sm">{{ $item['text'] }}</p><p class="mt-2 text-xs font-semibold text-emerald-700">{{ $item['staff'] }}</p></li>@empty<li class="text-sm text-slate-500">No information recorded for this period.</li>@endforelse</ul></div>@endforeach</section>
</div>
@endsection
