@extends('layouts.app')
@section('title', 'Printable Timesheet')
@section('section-label', 'Reporting and Documentation')
@section('page-title', 'Printable Timesheet')

@section('content')
<div class="mx-auto max-w-screen-2xl">
    <header class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><h2 class="text-3xl font-bold">Printable Timesheet</h2><p class="mt-2 text-slate-600">Review saved activities for a month, then print or export the official timesheet.</p></div>
        <div class="flex flex-wrap gap-3"><a target="_blank" href="{{ route('my-work.timesheet.print',['month'=>$period['month'],'year'=>$period['year']]) }}" class="rounded-xl bg-emerald-800 px-5 py-3 font-semibold text-white">Print Timesheet</a><a href="{{ route('my-work.timesheet.pdf',['month'=>$period['month'],'year'=>$period['year']]) }}" class="rounded-xl border border-emerald-700 px-5 py-3 font-semibold text-emerald-800">Download PDF</a><a href="{{ route('my-work.timesheet.csv',['month'=>$period['month'],'year'=>$period['year']]) }}" class="rounded-xl border border-slate-300 px-5 py-3 font-semibold">Export CSV</a></div>
    </header>
    <section class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <form method="GET" class="flex flex-wrap items-end gap-4"><label class="min-w-44 text-sm font-semibold">Month<select name="month" class="mt-2 w-full rounded-xl border-slate-300">@foreach(range(1,12) as $option)<option value="{{ $option }}" @selected($period['month']===$option)>{{ Carbon\CarbonImmutable::create(null,$option,1)->format('F') }}</option>@endforeach</select></label><label class="min-w-32 text-sm font-semibold">Year<select name="year" class="mt-2 w-full rounded-xl border-slate-300">@foreach(range(today()->year + 1,today()->year - 5) as $option)<option value="{{ $option }}" @selected($period['year']===$option)>{{ $option }}</option>@endforeach</select></label><button class="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Load Timesheet</button></form>
    </section>
    <section class="overflow-hidden rounded-2xl border border-slate-300 bg-white shadow-sm">
        <div class="border-b-4 border-blue-600 px-6 py-6 text-center"><p class="text-sm font-bold uppercase tracking-widest text-slate-700">Employee Performance Timesheet</p><h3 class="mt-1 text-2xl font-bold">{{ $period['label'] }}</h3><p class="mt-1 text-sm text-slate-600">Record of activities performed and hours worked</p></div>
        <dl class="grid border-b border-slate-300 text-sm sm:grid-cols-2 lg:grid-cols-3">@foreach([['Employee',$staff['name']],['Position',$staff['position'] ?: '—'],['Campus',$staff['campus'] ?: '—'],['Library',$staff['library'] ?: '—'],['Supervisor',$staff['supervisor'] ?: '—'],['Total Hours',$totalHours]] as [$label,$value])<div class="border-b border-r border-slate-200 px-4 py-3"><dt class="font-semibold text-slate-500">{{ $label }}</dt><dd class="mt-1 font-semibold text-slate-900">{{ $value }}</dd></div>@endforeach</dl>
        <div class="overflow-x-auto"><table class="min-w-full text-left text-xs"><thead class="bg-blue-600 text-white"><tr>@foreach(['Date','Day','Project','Activity / Task','Start','End','Hours','Output / Deliverable','Location'] as $heading)<th class="whitespace-nowrap border border-blue-700 px-3 py-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($entries as $entry)<tr><td class="whitespace-nowrap border border-slate-200 px-3 py-3">{{ $entry->work_date->format('d M Y') }}</td><td class="border border-slate-200 px-3 py-3">{{ $entry->work_date->format('l') }}</td><td class="min-w-44 border border-slate-200 px-3 py-3">{{ $entry->project->title }}</td><td class="min-w-72 border border-slate-200 px-3 py-3"><span class="font-semibold">{{ $entry->task->title }}</span><p class="mt-1 text-slate-600">{{ $entry->work_description }}</p></td><td class="border border-slate-200 px-3 py-3">{{ Carbon\Carbon::parse($entry->start_time)->format('H:i') }}</td><td class="border border-slate-200 px-3 py-3">{{ Carbon\Carbon::parse($entry->end_time)->format('H:i') }}</td><td class="border border-slate-200 px-3 py-3 text-right font-semibold">{{ number_format($entry->duration_minutes/60,2) }}</td><td class="min-w-56 border border-slate-200 px-3 py-3">{{ $entry->output_deliverable ?: '—' }}</td><td class="min-w-36 border border-slate-200 px-3 py-3">{{ $entry->work_location ?: '—' }}</td></tr>@empty<tr><td colspan="9" class="px-6 py-14 text-center text-sm text-slate-500">No activities were recorded for this period.</td></tr>@endforelse</tbody><tfoot><tr class="bg-slate-100 font-bold"><td colspan="6" class="border border-slate-200 px-3 py-3 text-right">Total hours worked</td><td class="border border-slate-200 px-3 py-3 text-right">{{ number_format($totalMinutes/60,2) }}</td><td colspan="2" class="border border-slate-200"></td></tr></tfoot></table></div>
        <div class="grid gap-10 px-8 py-12 text-sm sm:grid-cols-2"><div><div class="h-10 border-b border-slate-500"></div><p class="mt-2 font-semibold">Employee signature</p><p class="text-slate-500">{{ $staff['name'] }}</p></div><div><div class="h-10 border-b border-slate-500"></div><p class="mt-2 font-semibold">Supervisor signature</p><p class="text-slate-500">{{ $staff['supervisor'] ?: '—' }}</p></div></div>
    </section>
</div>
@endsection
