@extends('layouts.app')
@section('title', 'Campus Dashboard')
@section('page-title', 'Campus Dashboard')
@section('content')
<div class="space-y-7">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-sm font-bold uppercase tracking-wider text-emerald-700">Campus performance</p><h2 class="mt-1 text-3xl font-bold text-slate-900">{{ $campus?->name ?? 'Campus not assigned' }} Dashboard</h2><p class="mt-2 text-slate-600">Management visibility for {{ $period->format('F Y') }}. Task figures use current status for assignments made in this period.</p></div>
        <form method="GET" class="flex gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
            <select name="month" class="rounded-xl border-slate-300 text-sm">@foreach(range(1,12) as $month)<option value="{{ $month }}" @selected($period->month === $month)>{{ now()->month($month)->format('F') }}</option>@endforeach</select>
            <select name="year" class="rounded-xl border-slate-300 text-sm">@foreach(range(now()->year + 1, 2000) as $year)<option value="{{ $year }}" @selected($period->year === $year)>{{ $year }}</option>@endforeach</select>
            <button class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Apply</button>
        </form>
    </header>

    @if(!$campus || !$campus->is_active)
        <section class="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900">Your account does not have a valid active campus assignment. Contact an administrator to correct your staff profile.</section>
    @else
        <section class="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">
            @foreach([['Total Staff',$summary['total_staff']],['Active Staff',$summary['active_staff']],['Active Projects',$summary['active_projects']],['Active Tasks',$summary['active_tasks']],['Completed Tasks',$summary['completed_tasks']],['Tasks In Progress',$summary['in_progress_tasks']],['Overdue Tasks',$summary['overdue_tasks']],['Hours Recorded',App\Models\WorkEntry::formatMinutes($summary['minutes'])],['Staff Reporting',$summary['staff_reporting']],['Reports Pending',$summary['reports']->get('pending_review',0)]] as [$label,$value])
                <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-slate-900">{{ $value }}</p></div>
            @endforeach
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h3 class="text-lg font-bold">Staff Performance Overview</h3><p class="mt-1 text-sm text-slate-500">No ranking or inferred score is applied.</p></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>@foreach(['Staff Member','Position / Library','Hours','Days','Assigned','Completed','In Progress','Overdue','Completion','Report',''] as $h)<th class="px-4 py-3">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($staffRows as $row)<tr><td class="px-4 py-3 font-semibold text-slate-900">{{ $row['user']->name }}</td><td class="px-4 py-3 text-slate-600">{{ $row['user']->staffProfile?->position?->name ?? '—' }}<br><span class="text-xs">{{ $row['user']->staffProfile?->library?->name ?? '—' }}</span></td><td class="px-4 py-3">{{ App\Models\WorkEntry::formatMinutes($row['minutes']) }}</td><td class="px-4 py-3">{{ $row['days'] }}</td><td class="px-4 py-3">{{ $row['assigned'] }}</td><td class="px-4 py-3">{{ $row['completed'] }}</td><td class="px-4 py-3">{{ $row['in_progress'] }}</td><td class="px-4 py-3">{{ $row['overdue'] }}</td><td class="px-4 py-3">{{ number_format($row['completion_rate'],1) }}%</td><td class="px-4 py-3">{{ $row['report_status'] ? App\Models\MonthlyReport::label($row['report_status']) : 'No Report' }}</td><td class="px-4 py-3"><a class="font-semibold text-emerald-700" href="{{ route('campus-dashboard.staff', ['staff'=>$row['user'],'month'=>$period->month,'year'=>$period->year]) }}">View Details</a></td></tr>@empty<tr><td colspan="11" class="px-5 py-10 text-center text-slate-500">No staff are assigned to this campus.</td></tr>@endforelse
        </tbody></table></div></section>

        <section class="grid gap-6 xl:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Staff Task Status</h3><div class="mt-4 h-64"><canvas id="campus-task-status-chart"></canvas></div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Hours by Staff</h3><div class="mt-4 h-64"><canvas id="campus-hours-staff-chart"></canvas></div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Hours by Project</h3><div class="mt-4 h-64"><canvas id="campus-hours-project-chart"></canvas></div></div></section>
        <script type="application/json" id="campus-dashboard-chart-data">{!! json_encode($charts, JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>

        <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h3 class="text-lg font-bold">Campus Projects</h3></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr>@foreach(['Project','Status','Progress','Dates','Campus Staff','Tasks','Completed','In Progress','Overdue',''] as $h)<th class="px-4 py-3 text-left text-xs uppercase text-slate-500">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($projects as $project) @php($pt=$project->tasks)<tr><td class="px-4 py-3"><span class="font-mono text-xs text-emerald-700">{{ $project->project_code }}</span><br><span class="font-semibold">{{ $project->title }}</span></td><td class="px-4 py-3">{{ App\Models\Project::label($project->status) }}</td><td class="px-4 py-3">{{ number_format($project->progress_percentage,1) }}%</td><td class="px-4 py-3">{{ $project->start_date?->format('d M Y') ?? '—' }}<br>{{ $project->due_date?->format('d M Y') ?? '—' }}</td><td class="px-4 py-3">{{ $pt->flatMap->taskAssignees->pluck('user_id')->unique()->count() }}</td><td class="px-4 py-3">{{ $pt->count() }}</td><td class="px-4 py-3">{{ $pt->where('status','completed')->count() }}</td><td class="px-4 py-3">{{ $pt->where('status','in_progress')->count() }}</td><td class="px-4 py-3">{{ $pt->where('is_overdue',true)->count() }}</td><td class="px-4 py-3">@can('view',$project)<a href="{{ route('projects.show',$project) }}" class="font-semibold text-emerald-700">View</a>@endcan</td></tr>@empty<tr><td colspan="10" class="px-5 py-10 text-center text-slate-500">No active campus projects.</td></tr>@endforelse</tbody></table></div></section>

        <section class="grid gap-6 lg:grid-cols-2">@foreach(['in_progress'=>'Tasks In Progress','due_soon'=>'Tasks Due Soon','overdue'=>'Overdue Tasks','pending_review'=>'Tasks Pending Review'] as $key=>$heading)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">{{ $heading }}</h3><div class="mt-4 space-y-3">@forelse($taskSections[$key] as $task)<div class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><div><p class="font-mono text-xs text-emerald-700">{{ $task->task_code }}</p><p class="font-semibold">{{ $task->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $task->project?->title }} · {{ $task->assignees->pluck('name')->join(', ') ?: 'Unassigned' }}</p></div><span class="text-sm font-bold">{{ number_format($task->progress_percentage,1) }}%</span></div><div class="mt-2 flex justify-between text-xs text-slate-500"><span>{{ App\Models\Task::label($task->status) }} · Due {{ $task->due_date?->format('d M Y') ?? '—' }}</span>@can('view',$task)<a href="{{ route('tasks.show',$task) }}" class="font-semibold text-emerald-700">View</a>@endcan</div></div>@empty<p class="text-sm text-slate-500">No matching tasks.</p>@endforelse</div></div>@endforeach</section>

        <section class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Monthly Report Status</h3><div class="mt-4 grid grid-cols-2 gap-3">@foreach(['draft'=>'Draft','pending_review'=>'Pending Review','returned_for_correction'=>'Returned','approved'=>'Approved'] as $status=>$label)<div class="rounded-xl bg-slate-50 p-4"><p class="text-sm text-slate-500">{{ $label }}</p><p class="text-xl font-bold">{{ $summary['reports']->get($status,0) }}</p></div>@endforeach<div class="rounded-xl bg-slate-50 p-4"><p class="text-sm text-slate-500">No Report</p><p class="text-xl font-bold">{{ $summary['no_report'] }}</p></div></div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Recent Campus Activity</h3><div class="mt-4 space-y-4">@forelse($recentActivity as $activity)<div class="border-l-2 border-emerald-600 pl-3"><p class="font-semibold">{{ $activity['title'] }}</p><p class="text-sm text-slate-600">{{ $activity['description'] }}</p><p class="mt-1 text-xs text-slate-400">{{ $activity['user'] }} · {{ $activity['at']?->diffForHumans() }}</p></div>@empty<p class="text-sm text-slate-500">No recent campus activity.</p>@endforelse</div></div></section>
    @endif
</div>
@endsection
