@extends('layouts.app')
@section('title', 'Staff Performance')
@section('page-title', 'Staff Performance')
@section('content')
<div class="space-y-6"><a href="{{ route('campus-dashboard.index',['month'=>$period->month,'year'=>$period->year]) }}" class="text-sm font-semibold text-emerald-700">&larr; Back to Campus Dashboard</a><header class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-bold uppercase text-emerald-700">{{ $campus->name }} · {{ $period->format('F Y') }}</p><h2 class="mt-2 text-3xl font-bold">{{ $staff->name }}</h2><p class="mt-2 text-slate-600">{{ $staff->staffProfile?->position?->name ?? 'Position not set' }} · {{ $staff->staffProfile?->library?->name ?? 'Library not set' }}</p></header>
<section class="grid grid-cols-2 gap-4 md:grid-cols-4">@foreach([['Total Hours',$foundation['performance']['total_hours']],['Days Reported',$foundation['performance']['days_reported']],['Tasks Assigned',$foundation['performance']['tasks_assigned']],['Completed',$foundation['performance']['tasks_completed']],['In Progress / Pending',$foundation['performance']['pending_tasks']],['Overdue',$foundation['performance']['overdue_tasks']],['Completion Rate',number_format($foundation['performance']['completion_rate'],1).'%'],['Report Status',$foundation['report'] ? App\Models\MonthlyReport::label($foundation['status']) : 'No Report']] as [$label,$value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-bold">{{ $value }}</p></div>@endforeach</section>
<section class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Recent Work Entries</h3><div class="mt-4 space-y-3">@forelse($recentEntries as $entry)<div class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between"><p class="font-semibold">{{ $entry->work_date->format('d M Y') }}</p><span>{{ App\Models\WorkEntry::formatMinutes($entry->duration_minutes) }}</span></div><p class="mt-1 text-sm text-slate-600">{{ $entry->project?->title }} · {{ $entry->task?->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $entry->work_description }}</p>@can('view',$entry)<a href="{{ route('work-entries.show',$entry) }}" class="mt-2 inline-block text-sm font-semibold text-emerald-700">View authorized detail</a>@endcan</div>@empty<p class="text-sm text-slate-500">No work entries in this period.</p>@endforelse</div></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Assigned Tasks</h3><div class="mt-4 space-y-3">@forelse($assignedTasks as $task)<div class="rounded-xl border border-slate-200 p-4"><p class="font-mono text-xs text-emerald-700">{{ $task->task_code }}</p><p class="font-semibold">{{ $task->title }}</p><p class="text-sm text-slate-500">{{ App\Models\Task::label($task->status) }} · {{ number_format($task->progress_percentage,1) }}%</p>@can('view',$task)<a href="{{ route('tasks.show',$task) }}" class="text-sm font-semibold text-emerald-700">View task</a>@endcan</div>@empty<p class="text-sm text-slate-500">No active assigned tasks.</p>@endforelse</div></div></section>
<p class="text-sm text-slate-500">This management view is read-only. Work-entry editing and monthly-report review remain governed by their existing ownership and stored-reviewer policies.</p></div>
@endsection
