@extends('layouts.app')
@section('title','Organization Setup')
@section('section-label','Administrator')
@section('page-title','Organization Setup')
@section('content')
<div class="mx-auto max-w-screen-xl space-y-6"><header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-3xl font-bold">Organization Setup</h2><p class="mt-2 text-slate-600">Manage institutional master data with a non-destructive active/inactive lifecycle.</p></div><a href="{{ route('admin.organization.create',$entity) }}" class="rounded-xl bg-emerald-800 px-5 py-2.5 text-center font-semibold text-white">Add {{ str($label)->singular() }}</a></header>
<nav class="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm" aria-label="Organization sections">@foreach(['campuses'=>'Campuses','libraries'=>'Libraries','positions'=>'Positions','project-categories'=>'Project Categories'] as $key=>$tab)<a href="{{ route('admin.organization.index',$key) }}" class="rounded-xl px-4 py-2 text-sm font-semibold {{ $entity===$key ? 'bg-emerald-800 text-white' : 'text-slate-600 hover:bg-slate-100' }}">{{ $tab }}</a>@endforeach</nav>
<form method="GET" class="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><input name="search" value="{{ request('search') }}" placeholder="Search by name or code" aria-label="Search"><button class="rounded-xl border border-slate-300 px-5 py-2 font-semibold text-slate-700">Search</button></form>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase text-slate-500"><tr><th class="px-5 py-3.5">Name</th><th class="px-5 py-3.5">Code / Campus</th><th class="px-5 py-3.5">Status</th><th class="px-5 py-3.5">Usage</th><th class="px-5 py-3.5 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($records as $record)<tr><td class="px-5 py-4 font-semibold">{{ $record->name }}</td><td class="px-5 py-4 text-slate-600">{{ $record->code ?? '—' }}@if($entity==='libraries')<br><span class="text-xs">{{ $record->campus?->name }}</span>@endif</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $record->is_active && !$record->trashed() ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-600' }}">{{ $record->is_active && !$record->trashed() ? 'Active' : 'Inactive' }}</span></td><td class="px-5 py-4">{{ $record->{$entity==='project-categories' ? 'projects_count' : 'staff_profiles_count'} }} linked {{ $entity==='project-categories' ? 'projects' : 'staff profiles' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-3"><a href="{{ route('admin.organization.edit',[$entity,$record->id]) }}" class="font-semibold text-emerald-700">Edit</a>@if(!$record->trashed())<form method="POST" action="{{ route('admin.organization.toggle',[$entity,$record->id]) }}" onsubmit="return confirm('Change this record’s active status? Existing history will be preserved.')">@csrf @method('PATCH')<button class="font-semibold {{ $record->is_active ? 'text-red-700' : 'text-emerald-700' }}">{{ $record->is_active ? 'Deactivate' : 'Activate' }}</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="px-6 py-14 text-center text-slate-500">No {{ str($label)->lower() }} match the current search.</td></tr>@endforelse</tbody></table></div>@if($records->hasPages())<div class="border-t border-slate-200 p-4">{{ $records->links() }}</div>@endif</section></div>
@endsection
