@extends('layouts.report')
@section('title', 'Campus Consolidated Monthly Report - '.$data['identity']['period'])
@section('content')
<header class="masthead"><h1>Busitema University</h1><p class="system">Centralized Library Staff Performance System</p><h2>Campus Consolidated Monthly Report</h2></header>
<table class="meta"><tr><td><span class="label">Report Code</span>{{ $report?->report_code ?? 'Live draft — not assigned' }}</td><td><span class="label">Status</span><span class="badge">{{ $isFrozen ? 'Finalized' : 'Live Draft' }}</span></td><td><span class="label">Campus</span>{{ $data['identity']['campus'] }}</td><td><span class="label">Reporting Period</span>{{ $data['identity']['period'] }}</td></tr><tr><td colspan="2"><span class="label">Finalized By</span>{{ $report?->finalizer?->name ?: '—' }}</td><td colspan="2"><span class="label">Finalized At</span>{{ $report?->finalized_at?->format('d F Y, h:i A') ?: '—' }}</td></tr></table>
<h3>Campus Information and Performance Summary</h3><table class="summary"><tr>
@foreach([['Libraries',$data['campus']['libraries']],['Total Staff',$data['campus']['total_staff']],['Active Staff',$data['campus']['active_staff']],['Total Hours',$data['performance']['total_hours']],['Staff Reporting',$data['performance']['staff_reporting']],['Tasks Assigned',$data['performance']['tasks_assigned']],['Tasks Completed',$data['performance']['tasks_completed']],['In Progress',$data['performance']['tasks_in_progress']],['Pending Review',$data['performance']['pending_review']],['Overdue',$data['performance']['overdue']],['Completion Rate',number_format($data['performance']['completion_rate'],1).'%'],['Average Project Progress',number_format($data['performance']['average_project_progress'],1).'%']] as [$label,$value])<td><span class="label">{{ $label }}</span><span class="value">{{ $value }}</span></td>@if($loop->iteration % 4 === 0)</tr>@if(!$loop->last)<tr>@endif @endif @endforeach
</table>
<h3>Staff Performance Summary</h3><table class="data"><thead><tr>@foreach(['Staff','Position','Library','Hours','Days','Assigned','Completed','In Progress','Overdue','Completion','Report'] as $heading)<th>{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($data['staff_rows'] as $row)<tr>@foreach([$row['name'],$row['position'] ?: '—',$row['library'] ?: '—',$row['hours'],$row['days_reported'],$row['tasks_assigned'],$row['completed'],$row['in_progress'],$row['overdue'],number_format($row['completion_rate'],1).'% ',str($row['report_status'])->replace('_',' ')->title()] as $cell)<td>{{ $cell }}</td>@endforeach</tr>@empty<tr><td colspan="11">No active campus staff.</td></tr>@endforelse</tbody></table>
<h3>Project Performance Summary</h3><table class="data"><thead><tr>@foreach(['Code','Project','Status','Progress','Campus Staff','Tasks','Completed','In Progress','Overdue'] as $heading)<th>{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($data['project_rows'] as $row)<tr>@foreach([$row['code'],$row['title'],str($row['status'])->replace('_',' ')->title(),number_format($row['progress'],1).'%',implode(', ',$row['staff']),$row['task_count'],$row['completed'],$row['in_progress'],$row['overdue']] as $cell)<td>{{ $cell ?: '—' }}</td>@endforeach</tr>@empty<tr><td colspan="9">No campus project activity for this period.</td></tr>@endforelse</tbody></table>
<h3>Task and Monthly Report Status</h3><table class="data"><tr>@foreach($data['task_status'] as $status=>$count)<td><span class="label">{{ str($status)->replace('_',' ')->title() }}</span>{{ $count }}</td>@endforeach</tr><tr>@foreach($data['report_status'] as $status=>$count)<td><span class="label">Report: {{ str($status)->replace('_',' ')->title() }}</span>{{ $count }}</td>@endforeach</tr></table>
<h3>Consolidated Narrative</h3>@foreach(['achievements'=>'Achievements','challenges'=>'Challenges','corrective_actions'=>'Corrective Actions','support_required'=>'Support Required','planned_activities'=>'Planned Activities / Follow-up'] as $key=>$title)<div class="avoid-break"><strong>{{ $title }}</strong><ul>@forelse($data['narrative'][$key] as $item)<li>{{ $item['text'] }} <span class="muted">— {{ $item['staff'] }}</span></li>@empty<li class="muted">No information recorded.</li>@endforelse</ul></div>@endforeach
@endsection
