@extends('layouts.app')
@section('title','Staff Performance')
@section('section-label','Performance Oversight')
@section('page-title','Individual Performance')
@section('content')
<div class="mx-auto max-w-screen-2xl space-y-6"><header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-wide text-emerald-700">{{ $staff->staffProfile?->campus?->name }} · {{ $period->format('F Y') }}</p><h2 class="mt-1 text-3xl font-bold">{{ $staff->name }}</h2><p class="mt-2 text-slate-600">{{ $staff->staffProfile?->position?->name ?? 'Position not set' }} · Factual activity metrics only; no ranking or inferred quality score.</p></div><form method="GET" class="flex gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><select name="month">@foreach(range(1,12) as $month)<option value="{{ $month }}" @selected($period->month===$month)>{{ now()->month($month)->format('F') }}</option>@endforeach</select><select name="year">@foreach(range(now()->year+1,2000) as $year)<option @selected($period->year===$year)>{{ $year }}</option>@endforeach</select><button class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Apply</button></form></header>
<section class="grid grid-cols-2 gap-4 md:grid-cols-4 xl:grid-cols-7">@foreach([['Hours',App\Models\WorkEntry::formatMinutes($metrics['minutes'])],['Reporting Days',$metrics['days']],['Assigned Tasks',$metrics['assigned']],['Completed',$metrics['completed']],['Overdue',$metrics['overdue']],['Completion Rate',number_format($metrics['completion_rate'],1).'%'],['Projects Worked',$metrics['projects']]] as [$label,$value])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold">{{ $value }}</p></article>@endforeach</section>
<section class="grid gap-6 lg:grid-cols-2">@foreach([['performance-daily-chart','Daily Hours Trend'],['performance-task-chart','Task Status Distribution'],['performance-project-chart','Hours by Project'],['performance-location-chart','Work Location Distribution']] as [$id,$title])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">{{ $title }}</h3><div class="mt-4 h-72"><canvas id="{{ $id }}"></canvas></div></article>@endforeach</section>
<section class="grid gap-6 lg:grid-cols-2"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Monthly Report History</h3><div class="mt-4 divide-y divide-slate-100">@forelse($reports as $report)<div class="flex items-center justify-between gap-4 py-3"><div><p class="font-mono text-xs font-bold text-emerald-700">{{ $report->report_code }}</p><p class="text-sm">{{ now()->setYear($report->reporting_year)->setMonth($report->reporting_month)->format('F Y') }} · {{ App\Models\MonthlyReport::label($report->status) }}</p></div>@can('view',$report)<a href="{{ route('monthly-reports.reviews.show',$report) }}" class="text-sm font-semibold text-emerald-700">Open report</a>@endcan</div>@empty<p class="py-8 text-sm text-slate-500">No submitted monthly reports.</p>@endforelse</div></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Recent Period Activity</h3><div class="mt-4 space-y-3">@forelse($entries as $entry)<div class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><p class="font-semibold">{{ $entry->work_date->format('d M Y') }}</p><span class="text-sm">{{ App\Models\WorkEntry::formatMinutes($entry->duration_minutes) }}</span></div><p class="mt-1 text-sm text-slate-500">{{ $entry->project?->title }} · {{ $entry->work_location ?: 'Location not specified' }}</p></div>@empty<p class="text-sm text-slate-500">No work entries in this period.</p>@endforelse</div></article></section>
<p class="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">This oversight view is read-only and provides no route for editing another employee’s work entries or submitted snapshots.</p><script type="application/json" id="performance-chart-data">@json($charts)</script></div>
@endsection
