@extends('layouts.app')
@section('title','My Work')
@section('section-label','Daily Work')
@section('page-title','My Work')
@section('content')
<div class="mx-auto max-w-screen-2xl">
 <header class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-3xl font-bold text-slate-900">My Work</h2><p class="mt-2 text-slate-600">Record the work you perform on assigned tasks and subtasks.</p></div><div class="flex flex-wrap gap-3"><a href="{{ route('my-work.monthly-report') }}" class="rounded-xl border border-slate-300 px-5 py-3 text-center font-semibold text-slate-700">Monthly Report</a><a href="{{ route('my-work.timesheet') }}" class="rounded-xl border border-emerald-700 px-5 py-3 text-center font-semibold text-emerald-800">View Timesheet</a><a href="{{ route('work-entries.create') }}" class="rounded-xl bg-emerald-800 px-5 py-3 text-center font-semibold text-white">+ Add Daily Entry</a></div></header>
 <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><h3 class="text-lg font-bold">Recent Entries</h3></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase text-slate-500"><tr>@foreach(['Entry Code','Date','Project','Task','Subtask','Work Description','Start','End','Hours','View'] as $heading)<th class="whitespace-nowrap px-5 py-3.5">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($entries as $entry)<tr><td class="px-5 py-4 font-mono text-xs font-bold">{{ $entry->entry_code }}</td><td class="whitespace-nowrap px-5 py-4">{{ $entry->work_date->format('d M Y') }}</td><td class="min-w-52 px-5 py-4">{{ $entry->project->project_code }}<p class="mt-1 text-xs text-slate-500">{{ $entry->project->title }}</p></td><td class="min-w-52 px-5 py-4">{{ $entry->task->task_code }}<p class="mt-1 text-xs text-slate-500">{{ $entry->task->title }}</p></td><td class="min-w-44 px-5 py-4">{{ $entry->subtask?->subtask_code ?? '—' }}@if($entry->subtask)<p class="mt-1 text-xs text-slate-500">{{ $entry->subtask->title }}</p>@endif</td><td class="min-w-72 px-5 py-4"><p class="line-clamp-2">{{ $entry->work_description }}</p></td><td class="whitespace-nowrap px-5 py-4">{{ Carbon\Carbon::parse($entry->start_time)->format('H:i') }}</td><td class="whitespace-nowrap px-5 py-4">{{ Carbon\Carbon::parse($entry->end_time)->format('H:i') }}</td><td class="whitespace-nowrap px-5 py-4 font-semibold">{{ $entry->formatted_duration }}</td><td class="px-5 py-4"><a href="{{ route('work-entries.show',$entry) }}" class="font-semibold text-emerald-700">View</a></td></tr>@empty<tr><td colspan="10" class="px-6 py-14 text-center text-slate-500">No daily work entries recorded yet.</td></tr>@endforelse</tbody></table></div>@if($entries->hasPages())<div class="border-t px-5 py-4">{{ $entries->links() }}</div>@endif</section>
</div>
@endsection
