@extends('layouts.app')
@section('title','Timesheet')
@section('section-label','Daily Work')
@section('page-title','Timesheet')
@section('content')
<div class="mx-auto max-w-screen-2xl">
 <header class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-3xl font-bold text-slate-900">Timesheet</h2><p class="mt-2 text-slate-600">Review your recorded work, hours and assignments over a selected period.</p></div><div class="flex flex-wrap gap-3">@php($exportPeriod=['month'=>Carbon\CarbonImmutable::parse($filters['date_from'])->month,'year'=>Carbon\CarbonImmutable::parse($filters['date_from'])->year])<a target="_blank" href="{{ route('my-work.timesheet.print', $exportPeriod) }}" class="rounded-xl border border-emerald-700 px-5 py-3 font-semibold text-emerald-800">Print Month</a><a href="{{ route('my-work.timesheet.pdf', $exportPeriod) }}" class="rounded-xl border border-emerald-700 px-5 py-3 font-semibold text-emerald-800">Download PDF</a><a href="{{ route('my-work.timesheet.csv', $exportPeriod) }}" class="rounded-xl border border-emerald-700 px-5 py-3 font-semibold text-emerald-800">Export CSV</a><a href="{{ route('my-work.monthly-report') }}" class="rounded-xl border border-emerald-700 px-5 py-3 font-semibold text-emerald-800">Monthly Report</a><a href="{{ route('my-work.index') }}" class="rounded-xl border border-slate-300 px-5 py-3 font-semibold text-slate-700">Daily Entries</a><a href="{{ route('work-entries.create') }}" class="rounded-xl bg-emerald-800 px-5 py-3 font-semibold text-white">+ Add Daily Entry</a></div></header>

 @if($errors->any())<div class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <section class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><form method="GET" action="{{ route('my-work.timesheet') }}"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><label class="text-sm font-semibold">Date From<input type="date" name="date_from" value="{{ $filters['date_from'] }}" class="mt-2 w-full rounded-xl border-slate-300"></label><label class="text-sm font-semibold">Date To<input type="date" name="date_to" value="{{ $filters['date_to'] }}" class="mt-2 w-full rounded-xl border-slate-300"></label><label class="text-sm font-semibold">Project<select name="project_id" class="mt-2 w-full rounded-xl border-slate-300"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int)($filters['project_id'] ?? 0)===$project->id)>{{ $project->project_code }} — {{ $project->title }}</option>@endforeach</select></label><label class="text-sm font-semibold">Task<select name="task_id" class="mt-2 w-full rounded-xl border-slate-300"><option value="">All tasks</option>@foreach($tasks as $task)<option value="{{ $task->id }}" @selected((int)($filters['task_id'] ?? 0)===$task->id)>{{ $task->task_code }} — {{ $task->title }}</option>@endforeach</select></label><label class="text-sm font-semibold">Subtask<select name="subtask_id" class="mt-2 w-full rounded-xl border-slate-300"><option value="">All subtasks</option>@foreach($subtasks as $subtask)<option value="{{ $subtask->id }}" @selected((int)($filters['subtask_id'] ?? 0)===$subtask->id)>{{ $subtask->subtask_code }} — {{ $subtask->title }}</option>@endforeach</select></label></div><div class="mt-5 flex justify-end gap-3"><a href="{{ route('my-work.timesheet') }}" class="rounded-xl border border-slate-300 px-5 py-2.5 font-semibold text-slate-700">Reset Filters</a><button class="rounded-xl bg-slate-900 px-5 py-2.5 font-semibold text-white">Apply Filters</button></div></form></section>

 <section class="mb-6 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">@foreach([['Total Entries',number_format($totals['entries'])],['Total Hours',App\Models\WorkEntry::formatMinutes($totals['minutes'])],['Projects Worked On',number_format($totals['projects'])],['Tasks Worked On',number_format($totals['tasks'])],['Subtasks Worked On',number_format($totals['subtasks'])]] as [$label,$value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-slate-900">{{ $value }}</p></div>@endforeach</section>

 <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-6 py-5"><h3 class="text-lg font-bold">Recorded Work</h3><p class="font-bold text-emerald-800">Total Recorded Time: {{ App\Models\WorkEntry::formatMinutes($totals['minutes']) }}</p></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase text-slate-500"><tr>@foreach(['Entry Code','Work Date','Work Location','Project','Task','Subtask','Work Description','Start','End','Hours','View'] as $heading)<th class="whitespace-nowrap px-5 py-3.5">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($entries as $entry)<tr><td class="px-5 py-4 font-mono text-xs font-bold">{{ $entry->entry_code }}</td><td class="whitespace-nowrap px-5 py-4">{{ $entry->work_date->format('d M Y') }}</td><td class="min-w-40 px-5 py-4">{{ $entry->work_location ?: '—' }}</td><td class="min-w-52 px-5 py-4">{{ $entry->project->project_code }}<p class="mt-1 text-xs text-slate-500">{{ $entry->project->title }}</p></td><td class="min-w-52 px-5 py-4">{{ $entry->task->task_code }}<p class="mt-1 text-xs text-slate-500">{{ $entry->task->title }}</p></td><td class="min-w-44 px-5 py-4">@if($entry->subtask){{ $entry->subtask->subtask_code }}<p class="mt-1 text-xs text-slate-500">{{ $entry->subtask->title }}</p>@else<span class="text-slate-500">Direct task work</span>@endif</td><td class="min-w-72 px-5 py-4"><p class="line-clamp-2">{{ $entry->work_description }}</p></td><td class="whitespace-nowrap px-5 py-4">{{ Carbon\Carbon::parse($entry->start_time)->format('H:i') }}</td><td class="whitespace-nowrap px-5 py-4">{{ Carbon\Carbon::parse($entry->end_time)->format('H:i') }}</td><td class="whitespace-nowrap px-5 py-4 font-semibold">{{ $entry->formatted_duration }}</td><td class="px-5 py-4"><a href="{{ route('work-entries.show',$entry) }}" class="font-semibold text-emerald-700">View</a></td></tr>@empty<tr><td colspan="11" class="px-6 py-14 text-center text-slate-500">No work entries match the selected filters.</td></tr>@endforelse</tbody></table></div>@if($entries->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $entries->links() }}</div>@endif</section>
</div>
@endsection
