@extends('layouts.app')
@section('title','Add Daily Work Entry')
@section('section-label','Daily Work')
@section('page-title','Add Daily Work Entry')
@section('content')
<div class="mx-auto max-w-5xl"><a href="{{ route('my-work.index') }}" class="text-sm font-semibold text-emerald-700">&larr; Back to My Work</a><h2 class="mt-5 text-3xl font-bold">Add Daily Work Entry</h2><p class="mt-2 text-slate-600">Record the work completed during this work session.</p>
 @if($errors->any())<div class="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <form method="POST" action="{{ route('work-entries.store') }}" class="mt-7 space-y-6">@csrf
  <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="grid gap-6 md:grid-cols-2">
   <label class="text-sm font-semibold">Work Date<input type="date" name="work_date" max="{{ today()->format('Y-m-d') }}" required value="{{ old('work_date',today()->format('Y-m-d')) }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
   <label class="text-sm font-semibold">Work Location (optional)<input type="text" name="work_location" maxlength="255" value="{{ old('work_location') }}" class="mt-2 w-full rounded-xl border-slate-300" placeholder="e.g. Engineering Library, ICT Lab, Office, Remote"></label>
   <label class="text-sm font-semibold">Project<select name="project_id" required data-project class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int)old('project_id')===$project->id)>{{ $project->project_code }} — {{ $project->title }}</option>@endforeach</select></label>
   <label class="text-sm font-semibold">Task<select name="task_id" required data-task class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select project first</option>@foreach($tasks as $task)<option value="{{ $task->id }}" data-project-id="{{ $task->project_id }}" data-direct-allowed="{{ $task->taskAssignees->isNotEmpty() ? '1' : '0' }}" hidden @selected((int)old('task_id')===$task->id)>{{ $task->task_code }} — {{ $task->title }}</option>@endforeach</select></label>
   <label class="text-sm font-semibold md:col-span-2">Subtask (optional)<select name="subtask_id" data-subtask class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select a task first</option>@foreach($tasks as $task)@foreach($task->subtasks as $subtask)<option value="{{ $subtask->id }}" data-task-id="{{ $task->id }}" hidden @selected((int)old('subtask_id')===$subtask->id)>{{ $subtask->subtask_code }} — {{ $subtask->title }}</option>@endforeach @endforeach</select><span data-subtask-note class="mt-2 block text-xs font-normal text-slate-500"></span></label>
   <label class="text-sm font-semibold md:col-span-2">Work Description<textarea name="work_description" required minlength="10" maxlength="5000" rows="5" class="mt-2 w-full rounded-xl border-slate-300" placeholder="What did you actually do during this work session?">{{ old('work_description') }}</textarea></label>
   <label class="text-sm font-semibold">Start Time<input type="time" name="start_time" required value="{{ old('start_time') }}" data-start class="mt-2 w-full rounded-xl border-slate-300">@error('start_time')<span class="mt-1 block text-sm font-medium text-red-600">{{ $message }}</span>@enderror</label>
   <label class="text-sm font-semibold">End Time<input type="time" name="end_time" required value="{{ old('end_time') }}" data-end class="mt-2 w-full rounded-xl border-slate-300">@error('end_time')<span class="mt-1 block text-sm font-medium text-red-600">{{ $message }}</span>@enderror</label>
   <div class="rounded-xl bg-emerald-50 p-4 md:col-span-2"><p class="text-sm font-semibold text-emerald-900">Calculated Hours: <span data-duration>—</span></p><p class="mt-1 text-xs text-emerald-700">Calculated from start and end time. The server verifies this value.</p></div>
   <label class="text-sm font-semibold md:col-span-2">Output / Deliverable (optional)<textarea name="output_deliverable" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('output_deliverable') }}</textarea></label>
   <label class="text-sm font-semibold md:col-span-2">Challenge Encountered (optional)<textarea name="challenge_encountered" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('challenge_encountered') }}</textarea></label>
   <label class="text-sm font-semibold md:col-span-2">Corrective Action Taken (optional)<textarea name="corrective_action" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('corrective_action') }}</textarea></label>
   <label class="text-sm font-semibold md:col-span-2">Support Required (optional)<textarea name="support_required" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('support_required') }}</textarea></label>
   <label class="text-sm font-semibold md:col-span-2">Follow-up / Planned Next Activity (optional)<textarea name="planned_next_activity" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('planned_next_activity') }}</textarea></label>
   <label class="text-sm font-semibold md:col-span-2">Remarks (optional)<textarea name="remarks" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old('remarks') }}</textarea></label>
  </div></section><div class="flex justify-end gap-3"><a href="{{ route('my-work.index') }}" class="rounded-xl border border-slate-300 px-6 py-3 font-semibold">Cancel</a><button class="rounded-xl bg-emerald-800 px-6 py-3 font-semibold text-white">Record Daily Entry</button></div>
 </form>
</div>
<script>(()=>{const project=document.querySelector('[data-project]'),task=document.querySelector('[data-task]'),subtask=document.querySelector('[data-subtask]'),note=document.querySelector('[data-subtask-note]'),start=document.querySelector('[data-start]'),end=document.querySelector('[data-end]'),duration=document.querySelector('[data-duration]');const syncTasks=()=>{const projectId=project.value;[...task.options].slice(1).forEach(o=>o.hidden=o.dataset.projectId!==projectId);if(task.selectedOptions[0]?.hidden)task.value='';syncSubtasks()};const syncSubtasks=()=>{const taskId=task.value,directAllowed=task.selectedOptions[0]?.dataset.directAllowed==='1';let count=0;[...subtask.options].slice(1).forEach(o=>{o.hidden=o.dataset.taskId!==taskId;if(!o.hidden)count++});if(subtask.selectedOptions[0]?.hidden)subtask.value='';subtask.options[0].disabled=Boolean(taskId&&!directAllowed);subtask.required=Boolean(taskId&&!directAllowed);subtask.options[0].textContent=!taskId?'Select a task first':directAllowed?(count?'Record directly against task (optional)':'No assigned subtasks — record work directly against this task.'):'Select an assigned subtask';note.textContent=taskId&&count?'Only subtasks assigned to you are available.':''};const syncDuration=()=>{if(!start.value||!end.value){duration.textContent='—';return}const [sh,sm]=start.value.split(':').map(Number),[eh,em]=end.value.split(':').map(Number),minutes=(eh*60+em)-(sh*60+sm);duration.textContent=minutes>0?`${Number((minutes/60).toFixed(2))} hours`:'End time must be later than start time'};project.addEventListener('change',syncTasks);task.addEventListener('change',syncSubtasks);start.addEventListener('input',syncDuration);end.addEventListener('input',syncDuration);syncTasks();syncDuration()})();</script>
@endsection
