@extends('layouts.app')
@section('title','Edit Daily Work Entry')
@section('section-label','Daily Work')
@section('page-title','Edit Daily Work Entry')
@section('content')
<div class="mx-auto max-w-5xl">
 <a href="{{ route('work-entries.show',$workEntry) }}" class="text-sm font-semibold text-emerald-700">&larr; Back to Entry</a><h2 class="mt-5 text-3xl font-bold">Edit Daily Work Entry</h2><p class="mt-2 text-slate-600">Correct this source entry before resubmitting the returned monthly report.</p>
 @if($errors->any())<div class="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <form method="POST" action="{{ route('work-entries.update',$workEntry) }}" class="mt-7 space-y-6">@csrf @method('PATCH')
  <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="grid gap-6 md:grid-cols-2">
   <label class="text-sm font-semibold">Work Date<input type="date" name="work_date" max="{{ today()->format('Y-m-d') }}" required value="{{ old('work_date',$workEntry->work_date->format('Y-m-d')) }}" class="mt-2 w-full rounded-xl border-slate-300"></label><label class="text-sm font-semibold">Work Location (optional)<input type="text" name="work_location" maxlength="255" value="{{ old('work_location',$workEntry->work_location) }}" class="mt-2 w-full rounded-xl border-slate-300" placeholder="e.g. Engineering Library, ICT Lab, Office, Remote"></label>
   <label class="text-sm font-semibold">Project<select name="project_id" required data-project class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int)old('project_id',$workEntry->project_id)===$project->id)>{{ $project->project_code }} — {{ $project->title }}</option>@endforeach</select></label>
   <label class="text-sm font-semibold">Task<select name="task_id" required data-task class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select project first</option>@foreach($tasks as $task)<option value="{{ $task->id }}" data-project-id="{{ $task->project_id }}" data-direct-allowed="{{ $task->taskAssignees->isNotEmpty() ? '1' : '0' }}" hidden @selected((int)old('task_id',$workEntry->task_id)===$task->id)>{{ $task->task_code }} — {{ $task->title }}</option>@endforeach</select></label>
   <label class="text-sm font-semibold md:col-span-2">Subtask (optional)<select name="subtask_id" data-subtask class="mt-2 w-full rounded-xl border-slate-300"><option value="">Select a task first</option>@foreach($tasks as $task)@foreach($task->subtasks as $subtask)<option value="{{ $subtask->id }}" data-task-id="{{ $task->id }}" hidden @selected((int)old('subtask_id',$workEntry->subtask_id)===$subtask->id)>{{ $subtask->subtask_code }} — {{ $subtask->title }}</option>@endforeach @endforeach</select><span data-subtask-note class="mt-2 block text-xs font-normal text-slate-500"></span></label>
   <label class="text-sm font-semibold md:col-span-2">Work Description<textarea name="work_description" required minlength="10" maxlength="5000" rows="5" class="mt-2 w-full rounded-xl border-slate-300">{{ old('work_description',$workEntry->work_description) }}</textarea></label>
   <label class="text-sm font-semibold">Start Time<input type="time" name="start_time" required value="{{ old('start_time',Carbon\Carbon::parse($workEntry->start_time)->format('H:i')) }}" data-start class="mt-2 w-full rounded-xl border-slate-300"></label>
   <label class="text-sm font-semibold">End Time<input type="time" name="end_time" required value="{{ old('end_time',Carbon\Carbon::parse($workEntry->end_time)->format('H:i')) }}" data-end class="mt-2 w-full rounded-xl border-slate-300"></label>
   <div class="rounded-xl bg-emerald-50 p-4 md:col-span-2"><p class="text-sm font-semibold text-emerald-900">Calculated Hours: <span data-duration>—</span></p><p class="mt-1 text-xs text-emerald-700">Calculated from start and end time. The server verifies this value.</p></div>
   @foreach([['output_deliverable','Output / Deliverable'],['challenge_encountered','Challenge Encountered'],['corrective_action','Corrective Action Taken'],['support_required','Support Required'],['planned_next_activity','Follow-up / Planned Next Activity'],['remarks','Remarks']] as [$field,$label])<label class="text-sm font-semibold md:col-span-2">{{ $label }} (optional)<textarea name="{{ $field }}" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-300">{{ old($field,$workEntry->{$field}) }}</textarea></label>@endforeach
  </div></section><div class="flex justify-end gap-3"><a href="{{ route('work-entries.show',$workEntry) }}" class="rounded-xl border border-slate-300 px-6 py-3 font-semibold">Cancel</a><button class="rounded-xl bg-emerald-800 px-6 py-3 font-semibold text-white">Save Corrections</button></div>
 </form>
</div>
<script>(()=>{const project=document.querySelector('[data-project]'),task=document.querySelector('[data-task]'),subtask=document.querySelector('[data-subtask]'),note=document.querySelector('[data-subtask-note]'),start=document.querySelector('[data-start]'),end=document.querySelector('[data-end]'),duration=document.querySelector('[data-duration]');const syncSubtasks=()=>{const taskId=task.value,directAllowed=task.selectedOptions[0]?.dataset.directAllowed==='1';let count=0;[...subtask.options].slice(1).forEach(o=>{o.hidden=o.dataset.taskId!==taskId;if(!o.hidden)count++});if(subtask.selectedOptions[0]?.hidden)subtask.value='';subtask.options[0].disabled=Boolean(taskId&&!directAllowed);subtask.required=Boolean(taskId&&!directAllowed);subtask.options[0].textContent=!taskId?'Select a task first':directAllowed?(count?'Record directly against task (optional)':'No assigned subtasks — record work directly against this task.'):'Select an assigned subtask';note.textContent=taskId&&count?'Only subtasks assigned to you are available.':''};const syncTasks=()=>{const projectId=project.value;[...task.options].slice(1).forEach(o=>o.hidden=o.dataset.projectId!==projectId);if(task.selectedOptions[0]?.hidden)task.value='';syncSubtasks()};const syncDuration=()=>{if(!start.value||!end.value){duration.textContent='—';return}const [sh,sm]=start.value.split(':').map(Number),[eh,em]=end.value.split(':').map(Number),minutes=(eh*60+em)-(sh*60+sm);duration.textContent=minutes>0?`${Number((minutes/60).toFixed(2))} hours`:'End time must be later than start time'};project.addEventListener('change',syncTasks);task.addEventListener('change',syncSubtasks);start.addEventListener('input',syncDuration);end.addEventListener('input',syncDuration);syncTasks();syncDuration()})();</script>
@endsection
