@extends('layouts.app')
@section('title',$workEntry->entry_code)
@section('section-label','Daily Work')
@section('page-title','Daily Work Entry')
@section('content')
<div class="mx-auto max-w-5xl"><a href="{{ route('my-work.index') }}" class="text-sm font-semibold text-emerald-700">&larr; Back to My Work</a><header class="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="font-mono text-sm font-bold text-emerald-700">{{ $workEntry->entry_code }}</p><h2 class="mt-2 text-3xl font-bold">Daily Work Entry</h2></div>@can('update',$workEntry)<a href="{{ route('work-entries.edit',$workEntry) }}" class="rounded-xl bg-emerald-800 px-5 py-3 text-center font-semibold text-white">Edit Entry</a>@endcan</header>
 @can('update',$workEntry)<div class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">This reporting period was returned for correction. Update the required daily entries, then resubmit your monthly report.</div>@else @if($workEntry->user_id===auth()->id() && in_array($periodReportStatus,[App\Models\MonthlyReport::STATUS_PENDING_REVIEW,App\Models\MonthlyReport::STATUS_APPROVED],true))<div class="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">This entry is locked while the monthly report is under review or approved.</div>@endif @endcan
 <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><dl class="grid gap-6 sm:grid-cols-2">@foreach([['Staff Member',$workEntry->user->name],['Work Date',$workEntry->work_date->format('d F Y')],['Work Location',$workEntry->work_location ?: '—'],['Project',$workEntry->project->project_code.' — '.$workEntry->project->title],['Task',$workEntry->task->task_code.' — '.$workEntry->task->title],['Subtask',$workEntry->subtask ? $workEntry->subtask->subtask_code.' — '.$workEntry->subtask->title : 'Direct task entry'],['Start Time',Carbon\Carbon::parse($workEntry->start_time)->format('H:i')],['End Time',Carbon\Carbon::parse($workEntry->end_time)->format('H:i')],['Calculated Hours',$workEntry->formatted_duration],['Created At',$workEntry->created_at->format('d F Y, h:i A')]] as [$label,$value])<div><dt class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</dt><dd class="mt-2 font-semibold text-slate-800">{{ $value }}</dd></div>@endforeach</dl><div class="mt-7 grid gap-6 border-t pt-7"><div><h3 class="font-bold">Work Description</h3><p class="mt-2 whitespace-pre-line text-slate-600">{{ $workEntry->work_description }}</p></div><div class="rounded-xl border border-emerald-100 bg-emerald-50 p-5"><h3 class="font-bold text-emerald-900">Output / Deliverable</h3><p class="mt-2 whitespace-pre-line text-emerald-900">{{ $workEntry->output_deliverable ?: '—' }}</p></div>@foreach([['Challenge Encountered',$workEntry->challenge_encountered],['Corrective Action Taken',$workEntry->corrective_action],['Support Required',$workEntry->support_required],['Follow-up / Planned Next Activity',$workEntry->planned_next_activity]] as [$label,$value])@if(filled($value))<div><h3 class="font-bold">{{ $label }}</h3><p class="mt-2 whitespace-pre-line text-slate-600">{{ $value }}</p></div>@endif @endforeach<div><h3 class="font-bold">Remarks</h3><p class="mt-2 whitespace-pre-line text-slate-600">{{ $workEntry->remarks ?: '—' }}</p></div></div></section>
 <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex items-center justify-between gap-4"><div><h2 class="text-xl font-bold">Evidence ({{ $workEntry->evidences->count() }})</h2><p class="mt-1 text-sm text-slate-500">Files and links supporting this recorded work.</p></div>@can('addEvidence',$workEntry)<a href="{{ route('work-entries.evidence.create',$workEntry) }}" class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">+ Add Evidence</a>@endcan</div>
  @error('evidence')<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{{ $message }}</div>@enderror
  <div class="mt-6 grid gap-4">@forelse($workEntry->evidences as $evidence)<article class="rounded-xl border border-slate-200 p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="font-mono text-xs font-bold text-emerald-700">{{ $evidence->evidence_code }}</span><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{{ strtoupper($evidence->type) }}</span></div><h3 class="mt-2 font-bold text-slate-900">{{ $evidence->title }}</h3>@if($evidence->description)<p class="mt-2 whitespace-pre-line text-sm text-slate-600">{{ $evidence->description }}</p>@endif @if($evidence->type==='file')<p class="mt-2 break-all text-sm text-slate-600">{{ $evidence->original_filename }} <span class="text-slate-400">&middot; {{ $evidence->formatted_file_size }}</span></p>@else<p class="mt-2 break-all text-sm text-slate-600">{{ $evidence->url }}</p>@endif<p class="mt-2 text-xs text-slate-400">Added {{ $evidence->created_at->format('d F Y, h:i A') }}</p></div><div class="flex flex-wrap gap-2">@if($evidence->type==='file')<a href="{{ route('work-evidence.show',$evidence) }}" target="_blank" rel="noopener noreferrer" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">View</a><a href="{{ route('work-evidence.download',$evidence) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Download</a>@else<a href="{{ $evidence->url }}" target="_blank" rel="noopener noreferrer" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Open Link</a>@endif @can('delete',$evidence)<form method="POST" action="{{ route('work-evidence.destroy',$evidence) }}">@csrf @method('DELETE')<button class="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700" onclick="return confirm('Remove this evidence?')">Remove</button></form>@endcan</div></div></article>@empty<p class="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No evidence has been added to this work entry.</p>@endforelse</div>
 </section>
 <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 class="text-xl font-bold">Work Entry History</h2><p class="mt-1 text-sm text-slate-500">Recorded events for this daily work session.</p><div class="mt-6 space-y-0">@forelse($workEntry->activities as $activity)<article class="relative border-l-2 border-emerald-200 pb-6 pl-6 last:pb-0"><span class="absolute -left-2 top-1 h-3.5 w-3.5 rounded-full border-2 border-white bg-emerald-700"></span><div class="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><p class="font-bold text-slate-900">{{ $activity->event_label }}</p><p class="mt-1 text-sm text-slate-600">{{ $activity->description }}</p><p class="mt-2 text-xs font-semibold text-slate-500">{{ $activity->user->name }}</p></div><time class="shrink-0 text-xs text-slate-500" datetime="{{ $activity->created_at->toIso8601String() }}">{{ $activity->created_at->format('d M Y, h:i A') }}</time></div></article>@empty<p class="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No history has been recorded for this entry yet.</p>@endforelse</div></section>
</div>
@endsection
