@extends('layouts.app')
@section('title','Notifications')
@section('section-label','Account')
@section('page-title','Notifications')
@section('content')
<div class="mx-auto max-w-5xl space-y-6">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-3xl font-bold">Notifications</h2><p class="mt-2 text-slate-600">Workflow updates and items requiring your attention.</p></div>@if(auth()->user()->unreadNotifications()->exists())<form method="POST" action="{{ route('notifications.read-all') }}">@csrf<button class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Mark all as read</button></form>@endif</header>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="divide-y divide-slate-100">@forelse($notifications as $notification)<article class="flex gap-4 p-5 sm:p-6 {{ $notification->read_at ? '' : 'bg-emerald-50/40' }}"><span class="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full {{ $notification->read_at ? 'bg-slate-300' : 'bg-emerald-600' }}"></span><div class="min-w-0 flex-1"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 class="font-bold">{{ data_get($notification->data,'title','Notification') }}</h3><p class="mt-1 text-sm leading-6 text-slate-600">{{ data_get($notification->data,'message') }}</p><time class="mt-2 block text-xs text-slate-400">{{ $notification->created_at->format('d M Y, h:i A') }} · {{ $notification->created_at->diffForHumans() }}</time></div><form method="POST" action="{{ route('notifications.read',$notification) }}">@csrf<button class="shrink-0 text-sm font-semibold text-emerald-700">{{ data_get($notification->data,'url') ? 'Open' : ($notification->read_at ? 'Read' : 'Mark read') }}</button></form></div></div></article>@empty<div class="px-6 py-16 text-center"><p class="font-semibold text-slate-700">You’re all caught up</p><p class="mt-1 text-sm text-slate-500">Workflow notifications will appear here.</p></div>@endforelse</div>@if($notifications->hasPages())<div class="border-t border-slate-200 p-4">{{ $notifications->links() }}</div>@endif</section>
</div>
@endsection
