@extends('layouts.app')
@section('title', 'Campus Performance Detail')
@section('page-title', 'Campus Performance Detail')
@section('content')
<div class="space-y-7">
    <a href="{{ route('university-dashboard.index',['month'=>$period->month,'year'=>$period->year]) }}" class="text-sm font-semibold text-emerald-700">&larr; Back to University Dashboard</a>
    <header class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-bold uppercase text-emerald-700">{{ $period->format('F Y') }} · Read-only oversight</p><h2 class="mt-2 text-3xl font-bold">{{ $campus->name }}</h2><p class="mt-2 text-slate-600">Libraries: {{ $libraries->pluck('name')->join(', ') ?: 'None assigned' }}</p>@if($report)<a href="{{ route('campus-reports.show',$report) }}" class="mt-4 inline-block rounded-xl bg-emerald-800 px-4 py-2 font-semibold text-white">Open Finalized Report {{ $report->report_code }}</a>@else<p class="mt-4 text-sm font-semibold text-amber-700">Campus report: Not Finalized</p>@endif</header>
    <section class="grid grid-cols-2 gap-4 md:grid-cols-4">@foreach([['Total Staff',$summary['total_staff']],['Active Staff',$summary['active_staff']],['Hours',App\Models\WorkEntry::formatMinutes($summary['minutes'])],['Staff Reporting',$summary['staff_reporting']],['Active Tasks',$summary['active_tasks']],['Completed',$summary['completed_tasks']],['In Progress',$summary['in_progress_tasks']],['Overdue',$summary['overdue_tasks']],['Active Projects',$summary['active_projects']]] as [$label,$value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-bold">{{ $value }}</p></div>@endforeach</section>
    <x-campus-report-table title="Staff Performance" :headers="['Staff','Position','Library','Hours','Days','Assigned','Completed','In Progress','Overdue','Completion','Report']">@foreach($staffRows as $row)<tr>@foreach([$row['user']->name,$row['user']->staffProfile?->position?->name ?? '—',$row['user']->staffProfile?->library?->name ?? '—',App\Models\WorkEntry::formatMinutes($row['minutes']),$row['days'],$row['assigned'],$row['completed'],$row['in_progress'],$row['overdue'],number_format($row['completion_rate'],1).'%', $row['report_status'] ? App\Models\MonthlyReport::label($row['report_status']) : 'No Report'] as $cell)<td class="px-4 py-3">{{ $cell }}</td>@endforeach</tr>@endforeach</x-campus-report-table>
    <x-campus-report-table title="Project Performance" :headers="['Code','Project','Status','Stored Progress']">@foreach($projects as $project)<tr><td class="px-4 py-3 font-mono text-xs">{{ $project->project_code }}</td><td class="px-4 py-3">{{ $project->title }}</td><td class="px-4 py-3">{{ App\Models\Project::label($project->status) }}</td><td class="px-4 py-3">{{ number_format($project->progress_percentage,1) }}%</td></tr>@endforeach</x-campus-report-table>
    <p class="text-sm text-slate-500">This view does not provide work-entry, task, monthly-report, or campus-report mutation actions.</p>
</div>
@endsection
