@extends('layouts.app')
@section('title', 'University Librarian Dashboard')
@section('page-title', 'University Librarian Dashboard')
@section('content')
<div class="mb-4 flex justify-end"><a href="{{ route('university-dashboard.csv', ['month'=>$period->month,'year'=>$period->year]) }}" class="rounded-xl border border-emerald-700 bg-white px-4 py-2 font-semibold text-emerald-800">Export Institution CSV</a></div>
<div class="space-y-7">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-sm font-bold uppercase tracking-wider text-emerald-700">Institution-wide oversight</p><h2 class="mt-1 text-3xl font-bold text-slate-900">University Librarian Dashboard</h2><p class="mt-2 text-slate-600">Read-only library performance visibility for {{ $period->format('F Y') }}.</p></div>
        <form method="GET" class="flex gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><select name="month" class="rounded-xl border-slate-300 text-sm">@foreach(range(1,12) as $month)<option value="{{ $month }}" @selected($period->month === $month)>{{ now()->month($month)->format('F') }}</option>@endforeach</select><select name="year" class="rounded-xl border-slate-300 text-sm">@foreach(range(now()->year + 1,2000) as $year)<option value="{{ $year }}" @selected($period->year === $year)>{{ $year }}</option>@endforeach</select><button class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Apply</button></form>
    </header>

    <section class="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">
        @foreach([['Total Campuses',$summary['total_campuses']],['Total Libraries',$summary['total_libraries']],['Total Staff',$summary['total_staff']],['Active Staff',$summary['active_staff']],['Active Projects',$summary['active_projects']],['Active Tasks',$summary['active_tasks']],['Completed Tasks',$summary['completed_tasks']],['Tasks In Progress',$summary['in_progress_tasks']],['Overdue Tasks',$summary['overdue_tasks']],['Total Hours Recorded',App\Models\WorkEntry::formatMinutes($summary['minutes'])],['Staff Reporting',$summary['staff_reporting']],['Campus Reports Finalized',$summary['reports_finalized']],['Campus Reports Outstanding',$summary['reports_outstanding']]] as [$label,$value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-slate-900">{{ $value }}</p></div>@endforeach
    </section>

    <x-campus-report-table title="Campus Performance Overview" :headers="['Campus','Libraries','Total Staff','Active Staff','Hours','Staff Reporting','Tasks Assigned','Completed','In Progress','Overdue','Completion Rate','Active Projects','Campus Report Status','Action']">
        @forelse($campusRows as $row)<tr><td class="px-4 py-3 font-semibold">{{ $row['campus']->name }}</td>@foreach([$row['libraries'],$row['total_staff'],$row['active_staff'],App\Models\WorkEntry::formatMinutes($row['minutes']),$row['staff_reporting'],$row['assigned'],$row['completed'],$row['in_progress'],$row['overdue'],number_format($row['completion_rate'],1).'%',$row['active_projects']] as $cell)<td class="px-4 py-3">{{ $cell }}</td>@endforeach<td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $row['report'] ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">{{ $row['report'] ? 'Finalized' : 'Not Finalized' }}</span></td><td class="px-4 py-3"><a class="font-semibold text-emerald-700" href="{{ route('university-dashboard.campus',['campus'=>$row['campus'],'month'=>$period->month,'year'=>$period->year]) }}">View Details</a></td></tr>@empty<tr><td colspan="14" class="p-8 text-center text-slate-500">No active campuses.</td></tr>@endforelse
    </x-campus-report-table>

    <section class="grid gap-6 lg:grid-cols-2 xl:grid-cols-3">@foreach([['university-hours-campus-chart','Hours by Campus'],['university-task-status-chart','Task Status Across the University'],['university-completion-chart','Campus Completion Rates'],['university-report-chart','Campus Report Status'],['university-project-chart','Project Progress']] as [$id,$title])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">{{ $title }}</h3><div class="mt-4 h-64"><canvas id="{{ $id }}"></canvas></div></div>@endforeach</section>

    <x-campus-report-table title="Campus Reporting Status" :headers="['Campus','Campus Librarian','Report Status','Report Code','Finalized By','Finalized At','Action']">
        @foreach($reportRows as $row)<tr><td class="px-4 py-3 font-semibold">{{ $row['campus']->name }}</td><td class="px-4 py-3">{{ $row['librarian']?->name ?? 'Not assigned' }}</td><td class="px-4 py-3">{{ $row['report'] ? 'Finalized' : 'Not Finalized' }}</td><td class="px-4 py-3 font-mono text-xs">{{ $row['report']?->report_code ?? '—' }}</td><td class="px-4 py-3">{{ $row['report']?->finalizer?->name ?? '—' }}</td><td class="px-4 py-3">{{ $row['report']?->finalized_at?->format('d M Y, H:i') ?? '—' }}</td><td class="px-4 py-3">@if($row['report'])<a class="font-semibold text-emerald-700" href="{{ route('campus-reports.show',$row['report']) }}">Open Snapshot</a>@else<span class="text-slate-400">—</span>@endif</td></tr>@endforeach
    </x-campus-report-table>

    <x-campus-report-table title="Staff Performance Overview" :headers="['Staff Member','Campus','Library','Position','Hours','Days Reported','Tasks Assigned','Completed','In Progress','Overdue','Completion Rate','Monthly Report Status']">
        @foreach($staffRows as $row)<tr>@foreach([$row['user']->name,$row['campus']->name,$row['user']->staffProfile?->library?->name ?? '—',$row['user']->staffProfile?->position?->name ?? '—',App\Models\WorkEntry::formatMinutes($row['minutes']),$row['days'],$row['assigned'],$row['completed'],$row['in_progress'],$row['overdue'],number_format($row['completion_rate'],1).'%', $row['report_status'] ? App\Models\MonthlyReport::label($row['report_status']) : 'No Report'] as $cell)<td class="px-4 py-3">{{ $cell }}</td>@endforeach</tr>@endforeach
    </x-campus-report-table>

    <x-campus-report-table title="Project Performance Overview" :headers="['Project Code','Project','Status','Progress','Campuses','Staff','Tasks','Completed','In Progress','Overdue']">
        @foreach($projectRows as $row)<tr>@foreach([$row['project']->project_code,$row['project']->title,App\Models\Project::label($row['project']->status),number_format($row['project']->progress_percentage,1).'%', $row['project']->scope === 'university_wide' ? 'University-wide' : $row['project']->campuses->pluck('name')->join(', '),$row['staff'],$row['tasks'],$row['completed'],$row['in_progress'],$row['overdue']] as $cell)<td class="px-4 py-3">{{ $cell ?: '—' }}</td>@endforeach</tr>@endforeach
    </x-campus-report-table>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold">Recent Institution Activity</h3><div class="mt-4 space-y-4">@forelse($recentActivity as $activity)<div class="border-l-2 border-emerald-600 pl-3"><p class="font-semibold">{{ $activity['title'] }}</p><p class="text-sm text-slate-600">{{ $activity['description'] }}</p><p class="mt-1 text-xs text-slate-400">{{ $activity['user'] }} · {{ $activity['at']?->diffForHumans() }}</p></div>@empty<p class="text-sm text-slate-500">No recent institution activity.</p>@endforelse</div></section>
    <script type="application/json" id="university-dashboard-chart-data">@json($charts)</script>
</div>
@endsection
