@extends('layouts.app')
@section('title','Administration')
@section('section-label','Administrator')
@section('page-title','Administration')
@section('content')
<div class="mx-auto max-w-screen-2xl space-y-7"><header><h2 class="text-3xl font-bold">Administration</h2><p class="mt-2 text-slate-600">Application governance, access visibility, audit activity, and workflow health. This area contains no server or shell controls.</p></header>
<section><h3 class="mb-3 text-lg font-bold">Workflow Health</h3><div class="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-6">@foreach([['Pending task reviews',$health['pending_task_reviews']],['Pending reports',$health['pending_reports']],['Returned reports',$health['returned_reports']],['Inactive accounts',$health['inactive_accounts']],['Inactive profiles',$health['inactive_profiles']],['Active campuses',$health['active_campuses']]] as [$label,$value])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold">{{ $value }}</p></article>@endforeach</div></section>
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h3 class="text-lg font-bold">Roles and Permissions</h3><p class="mt-1 text-sm text-slate-500">Read-only governance overview. Core role definitions remain seed-controlled to prevent accidental escalation.</p></div><div class="grid gap-px bg-slate-200 md:grid-cols-2 xl:grid-cols-3">@foreach($roles as $role)<article class="bg-white p-5"><div class="flex justify-between"><h4 class="font-bold">{{ $role->name }}</h4><span class="text-xs text-slate-500">{{ $role->users_count }} users</span></div><div class="mt-3 flex flex-wrap gap-1.5">@foreach($role->permissions as $permission)<span class="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{{ $permission->name }}</span>@endforeach</div></article>@endforeach</div></section>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h3 class="text-lg font-bold">User Access Overview</h3></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr>@foreach(['User','Role','Campus / Library','Account','Profile','Last Login'] as $h)<th class="px-4 py-3">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@foreach($users as $user)<tr><td class="px-4 py-3"><span class="font-semibold">{{ $user->name }}</span><br><span class="text-xs text-slate-500">{{ $user->email }}</span></td><td class="px-4 py-3">{{ $user->getRoleNames()->join(', ') ?: 'None' }}</td><td class="px-4 py-3">{{ $user->staffProfile?->campus?->name ?? '—' }}<br><span class="text-xs text-slate-500">{{ $user->staffProfile?->library?->name }}</span></td><td class="px-4 py-3">{{ str($user->account_status)->title() }}</td><td class="px-4 py-3">{{ str($user->staffProfile?->status ?? 'Not assigned')->title() }}</td><td class="px-4 py-3">{{ $user->last_login_at?->format('d M Y, H:i') ?? 'Never' }}</td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 p-4">{{ $users->links() }}</div></section>
<div class="grid gap-6 xl:grid-cols-3"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2"><div class="border-b border-slate-200 p-5"><h3 class="text-lg font-bold">Consolidated Audit Activity</h3></div><div class="max-h-[38rem] divide-y divide-slate-100 overflow-y-auto">@forelse($activity as $item)<article class="p-4"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{{ $item['entity'] }}</span><strong>{{ str($item['action'])->replace('_',' ')->title() }}</strong></div><p class="mt-1 text-sm text-slate-600">{{ $item['description'] ?: 'Recorded workflow event.' }}</p><p class="mt-1 text-xs text-slate-400">{{ $item['actor'] }} · {{ $item['at']?->format('d M Y, H:i') }}</p></article>@empty<p class="p-8 text-sm text-slate-500">No activity records are available.</p>@endforelse</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-bold">System Information</h3><p class="mt-1 text-sm text-slate-500">Safe, read-only application metadata. Secrets and credentials are never shown.</p><dl class="mt-4 divide-y divide-slate-100">@foreach($system as $label=>$value)<div class="py-3"><dt class="text-xs font-semibold uppercase text-slate-500">{{ str($label)->replace('_',' ') }}</dt><dd class="mt-1 font-mono text-sm">{{ $value }}</dd></div>@endforeach</dl></section></div></div>
@endsection
