@extends('layouts.app')
@section('title',$subtask->subtask_code)
@section('section-label','Work Management')
@section('page-title','Subtask Detail')
@section('content')
<div class="mx-auto max-w-5xl"><a href="{{ route('tasks.show',$subtask->task) }}" class="text-sm font-semibold text-emerald-700">&larr; Back to Parent Task</a>
 <header class="mt-5"><p class="font-mono text-sm font-bold text-emerald-700">{{ $subtask->subtask_code }}</p><h2 class="mt-2 text-3xl font-bold">{{ $subtask->title }}</h2><p class="mt-3 text-slate-600">{{ $subtask->description ?: 'No description provided.' }}</p></header>
 <div class="mt-7 grid gap-6 lg:grid-cols-3"><section class="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-2"><dl class="grid gap-5 sm:grid-cols-2">@foreach([['Parent Task',$subtask->task->task_code.' — '.$subtask->task->title],['Assignee',$subtask->assignee?->name ?? 'Unassigned'],['Status',App\Models\Subtask::label($subtask->status)],['Priority',App\Models\Subtask::label($subtask->priority)],['Start Date',$subtask->start_date?->format('d F Y') ?? '—'],['Due Date',$subtask->due_date?->format('d F Y') ?? '—']] as [$label,$value])<div><dt class="text-xs font-bold uppercase text-slate-500">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $value }}</dd></div>@endforeach</dl><div class="mt-7"><div class="flex justify-between font-bold"><span>Progress</span><span>{{ number_format((float)$subtask->progress_percentage,2) }}%</span></div><div class="mt-2 h-3 rounded-full bg-slate-200"><div class="h-3 rounded-full bg-emerald-600" style="width:{{ $subtask->progress_percentage }}%"></div></div></div></section>
 @can('execute',$subtask)<section class="rounded-2xl border bg-white p-6 shadow-sm"><h3 class="font-bold">Subtask Actions</h3>@if($subtask->status==='not_started')<form method="POST" action="{{ route('subtasks.start',$subtask) }}" class="mt-4">@csrf<button class="w-full rounded-xl bg-blue-700 px-4 py-3 font-semibold text-white">Start Subtask</button></form>@endif
  @if(!in_array($subtask->status,['cancelled'],true))<form method="POST" action="{{ route('subtasks.progress',$subtask) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<label class="text-sm font-semibold">Progress<input type="number" step="0.01" min="0" max="100" name="progress_percentage" value="{{ $subtask->progress_percentage }}" class="mt-1 w-full rounded-xl border-slate-300"></label><textarea name="message" placeholder="Optional work remark" class="w-full rounded-xl border-slate-300"></textarea><button class="w-full rounded-xl bg-emerald-800 px-4 py-3 font-semibold text-white">Update Progress</button></form>@endif
  @if($subtask->status!=='completed' && $subtask->status!=='cancelled')<form method="POST" action="{{ route('subtasks.complete',$subtask) }}" class="mt-3">@csrf<button class="w-full rounded-xl border border-emerald-700 px-4 py-3 font-semibold text-emerald-800">Complete Subtask</button></form>@endif</section>@endcan</div>
</div>
@endsection
